-- Legacy coding-agent turn storage was removed before Agent Runtime V1.
-- Keep this migration version as a no-op so a clean database can replay the
-- historical migration chain without recreating the retired table.
