/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExportRouteImport } from './routes/export'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as LoginCompleteRouteImport } from './routes/login_.complete'
import { Route as AccountCompleteRouteImport } from './routes/account_.complete'
import { Route as InvitationsTokenCompleteRouteImport } from './routes/invitations.$token.complete'
import { Route as InvitationsTokenAcceptRouteImport } from './routes/invitations.$token.accept'
import { Route as HostsHostIdWorkspacesRouteImport } from './routes/hosts.$hostId.workspaces'
import { Route as AccountOrganizationsOrgIdRouteImport } from './routes/account_.organizations.$orgId'
import { Route as ProjectsProjectIdIssuesIssueIdRouteImport } from './routes/projects.$projectId_.issues.$issueId'
import { Route as HostsHostIdWorkspacesCreateRouteImport } from './routes/hosts.$hostId.workspaces_.create'
import { Route as HostsHostIdWorkspacesWorkspaceIdRouteImport } from './routes/hosts.$hostId.workspaces_.$workspaceId'
import { Route as HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport } from './routes/hosts.$hostId.workspaces.$workspaceId.vscode'
import { Route as ProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRouteImport } from './routes/projects.$projectId_.hosts.$hostId.workspaces.create.$draftId'
import { Route as ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRouteImport } from './routes/projects.$projectId_.issues.$issueId_.hosts.$hostId.workspaces.$workspaceId'
import { Route as ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRouteImport } from './routes/projects.$projectId_.issues.$issueId_.hosts.$hostId.workspaces.create.$draftId'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const LoginCompleteRoute = LoginCompleteRouteImport.update({
  id: '/login_/complete',
  path: '/login/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountCompleteRoute = AccountCompleteRouteImport.update({
  id: '/account_/complete',
  path: '/account/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsTokenCompleteRoute =
  InvitationsTokenCompleteRouteImport.update({
    id: '/invitations/$token/complete',
    path: '/invitations/$token/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvitationsTokenAcceptRoute = InvitationsTokenAcceptRouteImport.update({
  id: '/invitations/$token/accept',
  path: '/invitations/$token/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsHostIdWorkspacesRoute = HostsHostIdWorkspacesRouteImport.update({
  id: '/hosts/$hostId/workspaces',
  path: '/hosts/$hostId/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrganizationsOrgIdRoute =
  AccountOrganizationsOrgIdRouteImport.update({
    id: '/account_/organizations/$orgId',
    path: '/account/organizations/$orgId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdIssuesIssueIdRoute =
  ProjectsProjectIdIssuesIssueIdRouteImport.update({
    id: '/$projectId_/issues/$issueId',
    path: '/$projectId/issues/$issueId',
    getParentRoute: () => ProjectsRoute,
  } as any)
const HostsHostIdWorkspacesCreateRoute =
  HostsHostIdWorkspacesCreateRouteImport.update({
    id: '/hosts/$hostId/workspaces_/create',
    path: '/hosts/$hostId/workspaces/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const HostsHostIdWorkspacesWorkspaceIdRoute =
  HostsHostIdWorkspacesWorkspaceIdRouteImport.update({
    id: '/hosts/$hostId/workspaces_/$workspaceId',
    path: '/hosts/$hostId/workspaces/$workspaceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const HostsHostIdWorkspacesWorkspaceIdVscodeRoute =
  HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport.update({
    id: '/$workspaceId/vscode',
    path: '/$workspaceId/vscode',
    getParentRoute: () => HostsHostIdWorkspacesRoute,
  } as any)
const ProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute =
  ProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRouteImport.update({
    id: '/$projectId_/hosts/$hostId/workspaces/create/$draftId',
    path: '/$projectId/hosts/$hostId/workspaces/create/$draftId',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute =
  ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRouteImport.update(
    {
      id: '/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/$workspaceId',
      path: '/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId',
      getParentRoute: () => ProjectsRoute,
    } as any,
  )
const ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute =
  ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRouteImport.update(
    {
      id: '/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/create/$draftId',
      path: '/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId',
      getParentRoute: () => ProjectsRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/agents': typeof AgentsRoute
  '/dashboard': typeof DashboardRoute
  '/export': typeof ExportRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/account/complete': typeof AccountCompleteRoute
  '/login/complete': typeof LoginCompleteRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/account/organizations/$orgId': typeof AccountOrganizationsOrgIdRoute
  '/hosts/$hostId/workspaces': typeof HostsHostIdWorkspacesRouteWithChildren
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
  '/invitations/$token/complete': typeof InvitationsTokenCompleteRoute
  '/hosts/$hostId/workspaces/$workspaceId': typeof HostsHostIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces/create': typeof HostsHostIdWorkspacesCreateRoute
  '/projects/$projectId/issues/$issueId': typeof ProjectsProjectIdIssuesIssueIdRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
  '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId': typeof ProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId': typeof ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute
  '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId': typeof ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/agents': typeof AgentsRoute
  '/dashboard': typeof DashboardRoute
  '/export': typeof ExportRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/workflows': typeof WorkflowsRoute
  '/account/complete': typeof AccountCompleteRoute
  '/login/complete': typeof LoginCompleteRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/account/organizations/$orgId': typeof AccountOrganizationsOrgIdRoute
  '/hosts/$hostId/workspaces': typeof HostsHostIdWorkspacesRouteWithChildren
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
  '/invitations/$token/complete': typeof InvitationsTokenCompleteRoute
  '/hosts/$hostId/workspaces/$workspaceId': typeof HostsHostIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces/create': typeof HostsHostIdWorkspacesCreateRoute
  '/projects/$projectId/issues/$issueId': typeof ProjectsProjectIdIssuesIssueIdRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
  '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId': typeof ProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId': typeof ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute
  '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId': typeof ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/agents': typeof AgentsRoute
  '/dashboard': typeof DashboardRoute
  '/export': typeof ExportRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/account_/complete': typeof AccountCompleteRoute
  '/login_/complete': typeof LoginCompleteRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/account_/organizations/$orgId': typeof AccountOrganizationsOrgIdRoute
  '/hosts/$hostId/workspaces': typeof HostsHostIdWorkspacesRouteWithChildren
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
  '/invitations/$token/complete': typeof InvitationsTokenCompleteRoute
  '/hosts/$hostId/workspaces_/$workspaceId': typeof HostsHostIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces_/create': typeof HostsHostIdWorkspacesCreateRoute
  '/projects/$projectId_/issues/$issueId': typeof ProjectsProjectIdIssuesIssueIdRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
  '/projects/$projectId_/hosts/$hostId/workspaces/create/$draftId': typeof ProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/$workspaceId': typeof ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute
  '/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/create/$draftId': typeof ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/agents'
    | '/dashboard'
    | '/export'
    | '/login'
    | '/notifications'
    | '/projects'
    | '/workflows'
    | '/account/complete'
    | '/login/complete'
    | '/projects/$projectId'
    | '/projects/'
    | '/account/organizations/$orgId'
    | '/hosts/$hostId/workspaces'
    | '/invitations/$token/accept'
    | '/invitations/$token/complete'
    | '/hosts/$hostId/workspaces/$workspaceId'
    | '/hosts/$hostId/workspaces/create'
    | '/projects/$projectId/issues/$issueId'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
    | '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId'
    | '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId'
    | '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/agents'
    | '/dashboard'
    | '/export'
    | '/login'
    | '/notifications'
    | '/workflows'
    | '/account/complete'
    | '/login/complete'
    | '/projects/$projectId'
    | '/projects'
    | '/account/organizations/$orgId'
    | '/hosts/$hostId/workspaces'
    | '/invitations/$token/accept'
    | '/invitations/$token/complete'
    | '/hosts/$hostId/workspaces/$workspaceId'
    | '/hosts/$hostId/workspaces/create'
    | '/projects/$projectId/issues/$issueId'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
    | '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId'
    | '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId'
    | '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/agents'
    | '/dashboard'
    | '/export'
    | '/login'
    | '/notifications'
    | '/projects'
    | '/workflows'
    | '/account_/complete'
    | '/login_/complete'
    | '/projects/$projectId'
    | '/projects/'
    | '/account_/organizations/$orgId'
    | '/hosts/$hostId/workspaces'
    | '/invitations/$token/accept'
    | '/invitations/$token/complete'
    | '/hosts/$hostId/workspaces_/$workspaceId'
    | '/hosts/$hostId/workspaces_/create'
    | '/projects/$projectId_/issues/$issueId'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
    | '/projects/$projectId_/hosts/$hostId/workspaces/create/$draftId'
    | '/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/$workspaceId'
    | '/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/create/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AgentsRoute: typeof AgentsRoute
  DashboardRoute: typeof DashboardRoute
  ExportRoute: typeof ExportRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  WorkflowsRoute: typeof WorkflowsRoute
  AccountCompleteRoute: typeof AccountCompleteRoute
  LoginCompleteRoute: typeof LoginCompleteRoute
  AccountOrganizationsOrgIdRoute: typeof AccountOrganizationsOrgIdRoute
  HostsHostIdWorkspacesRoute: typeof HostsHostIdWorkspacesRouteWithChildren
  InvitationsTokenAcceptRoute: typeof InvitationsTokenAcceptRoute
  InvitationsTokenCompleteRoute: typeof InvitationsTokenCompleteRoute
  HostsHostIdWorkspacesWorkspaceIdRoute: typeof HostsHostIdWorkspacesWorkspaceIdRoute
  HostsHostIdWorkspacesCreateRoute: typeof HostsHostIdWorkspacesCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/login_/complete': {
      id: '/login_/complete'
      path: '/login/complete'
      fullPath: '/login/complete'
      preLoaderRoute: typeof LoginCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/complete': {
      id: '/account_/complete'
      path: '/account/complete'
      fullPath: '/account/complete'
      preLoaderRoute: typeof AccountCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$token/complete': {
      id: '/invitations/$token/complete'
      path: '/invitations/$token/complete'
      fullPath: '/invitations/$token/complete'
      preLoaderRoute: typeof InvitationsTokenCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$token/accept': {
      id: '/invitations/$token/accept'
      path: '/invitations/$token/accept'
      fullPath: '/invitations/$token/accept'
      preLoaderRoute: typeof InvitationsTokenAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId/workspaces': {
      id: '/hosts/$hostId/workspaces'
      path: '/hosts/$hostId/workspaces'
      fullPath: '/hosts/$hostId/workspaces'
      preLoaderRoute: typeof HostsHostIdWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/organizations/$orgId': {
      id: '/account_/organizations/$orgId'
      path: '/account/organizations/$orgId'
      fullPath: '/account/organizations/$orgId'
      preLoaderRoute: typeof AccountOrganizationsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId_/issues/$issueId': {
      id: '/projects/$projectId_/issues/$issueId'
      path: '/$projectId/issues/$issueId'
      fullPath: '/projects/$projectId/issues/$issueId'
      preLoaderRoute: typeof ProjectsProjectIdIssuesIssueIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/hosts/$hostId/workspaces_/create': {
      id: '/hosts/$hostId/workspaces_/create'
      path: '/hosts/$hostId/workspaces/create'
      fullPath: '/hosts/$hostId/workspaces/create'
      preLoaderRoute: typeof HostsHostIdWorkspacesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId/workspaces_/$workspaceId': {
      id: '/hosts/$hostId/workspaces_/$workspaceId'
      path: '/hosts/$hostId/workspaces/$workspaceId'
      fullPath: '/hosts/$hostId/workspaces/$workspaceId'
      preLoaderRoute: typeof HostsHostIdWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId/workspaces/$workspaceId/vscode': {
      id: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      path: '/$workspaceId/vscode'
      fullPath: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      preLoaderRoute: typeof HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport
      parentRoute: typeof HostsHostIdWorkspacesRoute
    }
    '/projects/$projectId_/hosts/$hostId/workspaces/create/$draftId': {
      id: '/projects/$projectId_/hosts/$hostId/workspaces/create/$draftId'
      path: '/$projectId/hosts/$hostId/workspaces/create/$draftId'
      fullPath: '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId'
      preLoaderRoute: typeof ProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/$workspaceId': {
      id: '/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/$workspaceId'
      path: '/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId'
      fullPath: '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId'
      preLoaderRoute: typeof ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/create/$draftId': {
      id: '/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/create/$draftId'
      path: '/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId'
      fullPath: '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId'
      preLoaderRoute: typeof ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdIssuesIssueIdRoute: typeof ProjectsProjectIdIssuesIssueIdRoute
  ProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute: typeof ProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute
  ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute: typeof ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute
  ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute: typeof ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdIssuesIssueIdRoute: ProjectsProjectIdIssuesIssueIdRoute,
  ProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute:
    ProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute,
  ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute:
    ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute,
  ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute:
    ProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface HostsHostIdWorkspacesRouteChildren {
  HostsHostIdWorkspacesWorkspaceIdVscodeRoute: typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
}

const HostsHostIdWorkspacesRouteChildren: HostsHostIdWorkspacesRouteChildren = {
  HostsHostIdWorkspacesWorkspaceIdVscodeRoute:
    HostsHostIdWorkspacesWorkspaceIdVscodeRoute,
}

const HostsHostIdWorkspacesRouteWithChildren =
  HostsHostIdWorkspacesRoute._addFileChildren(
    HostsHostIdWorkspacesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AgentsRoute: AgentsRoute,
  DashboardRoute: DashboardRoute,
  ExportRoute: ExportRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  WorkflowsRoute: WorkflowsRoute,
  AccountCompleteRoute: AccountCompleteRoute,
  LoginCompleteRoute: LoginCompleteRoute,
  AccountOrganizationsOrgIdRoute: AccountOrganizationsOrgIdRoute,
  HostsHostIdWorkspacesRoute: HostsHostIdWorkspacesRouteWithChildren,
  InvitationsTokenAcceptRoute: InvitationsTokenAcceptRoute,
  InvitationsTokenCompleteRoute: InvitationsTokenCompleteRoute,
  HostsHostIdWorkspacesWorkspaceIdRoute: HostsHostIdWorkspacesWorkspaceIdRoute,
  HostsHostIdWorkspacesCreateRoute: HostsHostIdWorkspacesCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
