// This file was auto-generated by api-types' shared remote contract generator.
// Do not edit manually.

// Electric row types
export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null;

export type Project = { id: string, organization_id: string, name: string, color: string, sort_order: number, created_at: string, updated_at: string, };

export type Notification = { id: string, organization_id: string, user_id: string, notification_type: NotificationType, payload: NotificationPayload, task_id: string | null, comment_id: string | null, seen: boolean, dismissed_at: string | null, created_at: string, };

export type NotificationGroupKind = "single" | "task_changes" | "status_changes" | "comments" | "reactions" | "task_deleted";

export type NotificationPayload = { deeplink_path?: string | null, task_id?: string | null, task_simple_id?: string | null, task_title?: string | null, actor_user_id?: string | null, comment_preview?: string | null, old_status_id?: string | null, new_status_id?: string | null, old_status_name?: string | null, new_status_name?: string | null, new_title?: string | null, old_priority?: TaskPriority | null, new_priority?: TaskPriority | null, assignee_user_id?: string | null, emoji?: string | null, };

export type NotificationType = "task_comment_added" | "task_status_changed" | "task_assignee_changed" | "task_priority_changed" | "task_unassigned" | "task_comment_reaction" | "task_deleted" | "task_title_changed" | "task_description_changed";

export type Workspace = { id: string, project_id: string, owner_user_id: string, task_id: string | null, local_workspace_id: string | null, name: string | null, archived: boolean, files_changed: number | null, lines_added: number | null, lines_removed: number | null, created_at: string, updated_at: string, };

export type ProjectStatus = { id: string, project_id: string, name: string, color: string, sort_order: number, hidden: boolean, created_at: string, };

export type Tag = { id: string, project_id: string, name: string, color: string, };

export type Task = { id: string, project_id: string, task_number: number, simple_id: string, status_id: string, title: string, description: string | null, priority: TaskPriority | null, start_date: string | null, target_date: string | null, completed_at: string | null, sort_order: number, parent_task_id: string | null, parent_task_sort_order: number | null, extension_metadata: JsonValue, creator_user_id: string | null, created_at: string, updated_at: string, };

export type TaskAssignee = { id: string, task_id: string, user_id: string, assigned_at: string, };

export type Blob = { id: string, project_id: string, blob_path: string, thumbnail_blob_path: string | null, original_name: string, mime_type: string | null, size_bytes: bigint, hash: string, width: number | null, height: number | null, created_at: string, updated_at: string, };

export type Attachment = { id: string, blob_id: string, task_id: string | null, comment_id: string | null, created_at: string, expires_at: string | null, };

export type AttachmentWithBlob = { id: string, blob_id: string, task_id: string | null, comment_id: string | null, created_at: string, expires_at: string | null, blob_path: string, thumbnail_blob_path: string | null, original_name: string, mime_type: string | null, size_bytes: bigint, hash: string, width: number | null, height: number | null, };

export type TaskFollower = { id: string, task_id: string, user_id: string, };

export type TaskTag = { id: string, task_id: string, tag_id: string, };

export type TaskRelationship = { id: string, task_id: string, related_task_id: string, relationship_type: TaskRelationshipType, created_at: string, };

export type TaskRelationshipType = "blocking" | "related" | "has_duplicate";

export type TaskComment = { id: string, task_id: string, author_id: string | null, parent_id: string | null, message: string, created_at: string, updated_at: string, };

export type TaskCommentReaction = { id: string, comment_id: string, user_id: string, emoji: string, created_at: string, };

export type TaskPriority = "urgent" | "high" | "medium" | "low";

export type TaskSortField = "sort_order" | "priority" | "created_at" | "updated_at" | "title";

export type ListTasksQuery = { project_id: string, };

export type SearchTasksRequest = { project_id: string, status_id?: string, status_ids?: Array<string>, priority?: TaskPriority, parent_task_id?: string, search?: string, simple_id?: string, assignee_user_id?: string, tag_id?: string, tag_ids?: Array<string>, sort_field?: TaskSortField, sort_direction?: SortDirection, limit?: number, offset?: number, };

export type ListTasksResponse = { tasks: Array<Task>, total_count: number, limit: number, offset: number, };

export type PullRequestStatus = "open" | "merged" | "closed";

export type PullRequest = { id: string, url: string, number: number, status: PullRequestStatus, merged_at: string | null, merge_commit_sha: string | null, target_branch_name: string, project_id: string, task_id: string, workspace_id: string | null, created_at: string, updated_at: string, };

export type PullRequestTask = { id: string, pull_request_id: string, task_id: string, };

export type CreatePullRequestTaskRequest = {
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, task_id: string, url: string, number: number, status: PullRequestStatus, merged_at: string | null, merge_commit_sha: string | null, target_branch_name: string, };

export type SortDirection = "asc" | "desc";

export type UserData = { user_id: string, first_name: string | null, last_name: string | null, username: string | null, };

export type User = { id: string, email: string, first_name: string | null, last_name: string | null, username: string | null, created_at: string, updated_at: string, };

export type RelayHost = { id: string, owner_user_id: string, machine_id: string, name: string, status: string, last_seen_at: string | null, agent_version: string | null, created_at: string, updated_at: string, access_role: string, };

export type ListRelayHostsResponse = { hosts: Array<RelayHost>, };

export type CreateRemoteSessionResponse = { session_id: string, };

export enum MemberRole { ADMIN = "ADMIN", MEMBER = "MEMBER" }

export type OrganizationMember = { organization_id: string, user_id: string, role: MemberRole, joined_at: string, last_seen_at: string | null, };

export type CreateProjectRequest = {
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, organization_id: string, name: string, color: string, };

export type UpdateProjectRequest = { name: string | null, color: string | null, sort_order: number | null, };

export type UpdateNotificationRequest = { seen: boolean | null, };

export type CreateTagRequest = {
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, project_id: string, name: string, color: string, };

export type UpdateTagRequest = { name: string | null, color: string | null, };

export type CreateProjectStatusRequest = {
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, project_id: string, name: string, color: string, sort_order: number, hidden: boolean, };

export type UpdateProjectStatusRequest = { name: string | null, color: string | null, sort_order: number | null, hidden: boolean | null, };

export type CreateTaskRequest = {
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, project_id: string, status_id: string, title: string, description: string | null, priority: TaskPriority | null, start_date: string | null, target_date: string | null, completed_at: string | null, sort_order: number, parent_task_id: string | null, parent_task_sort_order: number | null, extension_metadata: JsonValue, };

export type UpdateTaskRequest = { status_id?: string | null, title?: string | null, description?: string | null | null, priority?: TaskPriority | null | null, start_date?: string | null | null, target_date?: string | null | null, completed_at?: string | null | null, sort_order?: number | null, parent_task_id?: string | null | null, parent_task_sort_order?: number | null | null, extension_metadata?: JsonValue | null, };

export type CreateTaskAssigneeRequest = {
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, task_id: string, user_id: string, };

export type CreateTaskFollowerRequest = {
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, task_id: string, user_id: string, };

export type CreateTaskTagRequest = {
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, task_id: string, tag_id: string, };

export type CreateTaskRelationshipRequest = {
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, task_id: string, related_task_id: string, relationship_type: TaskRelationshipType, };

export type CreateTaskCommentRequest = {
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, task_id: string, message: string, parent_id: string | null, };

export type UpdateTaskCommentRequest = { message: string | null, parent_id: string | null | null, };

export type CreateTaskCommentReactionRequest = {
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, comment_id: string, emoji: string, };

export type UpdateTaskCommentReactionRequest = { emoji: string | null, };

export type InitUploadRequest = { project_id: string, filename: string, size_bytes: number, hash: string, };

export type InitUploadResponse = { upload_url: string, upload_id: string, expires_at: string, skip_upload: boolean, existing_blob_id: string | null, };

export type ConfirmUploadRequest = { project_id: string, upload_id: string, filename: string, content_type?: string, size_bytes: number, hash: string, task_id?: string, comment_id?: string, };

export type CommitAttachmentsRequest = { attachment_ids: Array<string>, };

export type CommitAttachmentsResponse = { attachments: Array<AttachmentWithBlob>, };

export type AttachmentUrlResponse = { url: string, };

export type ExportRequest = { organization_id: string,
/**
 * If empty, exports all projects in the organization.
 */
project_ids: Array<string>, include_attachments: boolean, };

// Shape definition interface
export interface ShapeDefinition<T> {
  readonly table: string;
  readonly params: readonly string[];
  readonly url: string;
  readonly fallbackUrl: string;
  readonly _type: T;  // Phantom field for type inference (not present at runtime)
}

// Helper to create type-safe shape definitions
function defineShape<T>(
  table: string,
  params: readonly string[],
  url: string,
  fallbackUrl: string
): ShapeDefinition<T> {
  return { table, params, url, fallbackUrl } as ShapeDefinition<T>;
}

// Individual shape definitions with embedded types
export const PROJECTS_SHAPE = defineShape<Project>(
  'projects',
  ['organization_id'] as const,
  '/v1/shape/projects',
  '/v1/fallback/projects'
);

export const NOTIFICATIONS_SHAPE = defineShape<Notification>(
  'notifications',
  ['user_id'] as const,
  '/v1/shape/notifications',
  '/v1/fallback/notifications'
);

export const ORGANIZATION_MEMBERS_SHAPE = defineShape<OrganizationMember>(
  'organization_member_metadata',
  ['organization_id'] as const,
  '/v1/shape/organization_members',
  '/v1/fallback/organization_members'
);

export const USERS_SHAPE = defineShape<User>(
  'users',
  ['organization_id'] as const,
  '/v1/shape/users',
  '/v1/fallback/users'
);

export const PROJECT_TAGS_SHAPE = defineShape<Tag>(
  'tags',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/tags',
  '/v1/fallback/tags'
);

export const PROJECT_PROJECT_STATUSES_SHAPE = defineShape<ProjectStatus>(
  'project_statuses',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/project_statuses',
  '/v1/fallback/project_statuses'
);

export const PROJECT_TASKS_SHAPE = defineShape<Task>(
  'issues',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/tasks',
  '/v1/fallback/tasks'
);

export const USER_WORKSPACES_SHAPE = defineShape<Workspace>(
  'workspaces',
  ['owner_user_id'] as const,
  '/v1/shape/user/workspaces',
  '/v1/fallback/user_workspaces'
);

export const PROJECT_WORKSPACES_SHAPE = defineShape<Workspace>(
  'workspaces',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/workspaces',
  '/v1/fallback/project_workspaces'
);

export const PROJECT_TASK_ASSIGNEES_SHAPE = defineShape<TaskAssignee>(
  'issue_assignees',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/task_assignees',
  '/v1/fallback/task_assignees'
);

export const PROJECT_TASK_FOLLOWERS_SHAPE = defineShape<TaskFollower>(
  'issue_followers',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/task_followers',
  '/v1/fallback/task_followers'
);

export const PROJECT_TASK_TAGS_SHAPE = defineShape<TaskTag>(
  'issue_tags',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/task_tags',
  '/v1/fallback/task_tags'
);

export const PROJECT_TASK_RELATIONSHIPS_SHAPE = defineShape<TaskRelationship>(
  'issue_relationships',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/task_relationships',
  '/v1/fallback/task_relationships'
);

export const PROJECT_PULL_REQUESTS_SHAPE = defineShape<PullRequest>(
  'pull_requests',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/pull_requests',
  '/v1/fallback/pull_requests'
);

export const PROJECT_PULL_REQUEST_TASKS_SHAPE = defineShape<PullRequestTask>(
  'pull_request_issues',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/pull_request_tasks',
  '/v1/fallback/pull_request_tasks'
);

export const TASK_COMMENTS_SHAPE = defineShape<TaskComment>(
  'issue_comments',
  ['task_id'] as const,
  '/v1/shape/task/{task_id}/comments',
  '/v1/fallback/task_comments'
);

export const TASK_REACTIONS_SHAPE = defineShape<TaskCommentReaction>(
  'issue_comment_reactions',
  ['task_id'] as const,
  '/v1/shape/task/{task_id}/reactions',
  '/v1/fallback/task_comment_reactions'
);

// =============================================================================
// Mutation Definitions
// =============================================================================

// Mutation definition interface
export interface MutationDefinition<TRow, TCreate = unknown, TUpdate = unknown> {
  readonly name: string;
  readonly url: string;
  readonly _rowType: TRow;  // Phantom field for type inference (not present at runtime)
  readonly _createType: TCreate;  // Phantom field for type inference (not present at runtime)
  readonly _updateType: TUpdate;  // Phantom field for type inference (not present at runtime)
}

// Helper to create type-safe mutation definitions
function defineMutation<TRow, TCreate, TUpdate>(
  name: string,
  url: string
): MutationDefinition<TRow, TCreate, TUpdate> {
  return { name, url } as MutationDefinition<TRow, TCreate, TUpdate>;
}

// Individual mutation definitions
export const PROJECT_MUTATION = defineMutation<Project, CreateProjectRequest, UpdateProjectRequest>(
  'Project',
  '/v1/projects'
);

export const NOTIFICATION_MUTATION = defineMutation<Notification, unknown, UpdateNotificationRequest>(
  'Notification',
  '/v1/notifications'
);

export const TAG_MUTATION = defineMutation<Tag, CreateTagRequest, UpdateTagRequest>(
  'Tag',
  '/v1/tags'
);

export const PROJECT_STATUS_MUTATION = defineMutation<ProjectStatus, CreateProjectStatusRequest, UpdateProjectStatusRequest>(
  'ProjectStatus',
  '/v1/project_statuses'
);

export const TASK_MUTATION = defineMutation<Task, CreateTaskRequest, UpdateTaskRequest>(
  'Task',
  '/v1/tasks'
);

export const TASK_ASSIGNEE_MUTATION = defineMutation<TaskAssignee, CreateTaskAssigneeRequest, unknown>(
  'TaskAssignee',
  '/v1/task_assignees'
);

export const TASK_FOLLOWER_MUTATION = defineMutation<TaskFollower, CreateTaskFollowerRequest, unknown>(
  'TaskFollower',
  '/v1/task_followers'
);

export const TASK_TAG_MUTATION = defineMutation<TaskTag, CreateTaskTagRequest, unknown>(
  'TaskTag',
  '/v1/task_tags'
);

export const TASK_RELATIONSHIP_MUTATION = defineMutation<TaskRelationship, CreateTaskRelationshipRequest, unknown>(
  'TaskRelationship',
  '/v1/task_relationships'
);

export const TASK_COMMENT_MUTATION = defineMutation<TaskComment, CreateTaskCommentRequest, UpdateTaskCommentRequest>(
  'TaskComment',
  '/v1/task_comments'
);

export const TASK_COMMENT_REACTION_MUTATION = defineMutation<TaskCommentReaction, CreateTaskCommentReactionRequest, UpdateTaskCommentReactionRequest>(
  'TaskCommentReaction',
  '/v1/task_comment_reactions'
);

export const PULL_REQUEST_TASK_MUTATION = defineMutation<PullRequestTask, CreatePullRequestTaskRequest, unknown>(
  'PullRequestTask',
  '/v1/pull_request_tasks'
);

// Type helpers to extract types from a mutation definition
export type MutationRowType<M extends MutationDefinition<unknown>> = M extends MutationDefinition<infer R> ? R : never;
export type MutationCreateType<M extends MutationDefinition<unknown, unknown>> = M extends MutationDefinition<unknown, infer C> ? C : never;
export type MutationUpdateType<M extends MutationDefinition<unknown, unknown, unknown>> = M extends MutationDefinition<unknown, unknown, infer U> ? U : never;
