// This file was generated by `crates/core/src/bin/generate_types.rs`.

// Do not edit this file manually.

// If you are an AI, and you absolutely have to edit this file, please confirm with the user first.

export type Repo = { id: string, path: string, name: string, display_name: string, setup_script: string | null, cleanup_script: string | null, archive_script: string | null, copy_files: string | null, parallel_setup_script: boolean, dev_server_script: string | null, default_target_branch: string | null, default_working_dir: string | null, created_at: Date, updated_at: Date, };

export type Project = { id: string, name: string, default_agent_working_dir: string | null, remote_project_id: string | null, created_at: Date, updated_at: Date, };

export type ProjectListItem = { id: string, name: string, created_at: string, updated_at: string, };

export type ProjectCursor = { updated_at: string, id: string, };

export type ProjectPage = { projects: Array<ProjectListItem>, next_cursor: ProjectCursor | null, };

export type UpdateRepo = { display_name?: string | null, setup_script?: string | null, cleanup_script?: string | null, archive_script?: string | null, copy_files?: string | null, parallel_setup_script?: boolean | null, dev_server_script?: string | null, default_target_branch?: string | null, default_working_dir?: string | null, };

export type SearchResult = { path: string, is_file: boolean, match_type: SearchMatchType, 
/**
 * Ranking score based on git history (higher = more recently/frequently edited)
 */
score: bigint, };

export type SearchMatchType = "FileName" | "DirectoryName" | "FullPath";

export type WorkspaceRepo = { id: string, workspace_id: string, repo_id: string, target_branch: string, created_at: Date, updated_at: Date, };

export type CreateWorkspaceRepo = { repo_id: string, target_branch: string, };

export type RepoWithTargetBranch = { target_branch: string, id: string, path: string, name: string, display_name: string, setup_script: string | null, cleanup_script: string | null, archive_script: string | null, copy_files: string | null, parallel_setup_script: boolean, dev_server_script: string | null, default_target_branch: string | null, default_working_dir: string | null, created_at: Date, updated_at: Date, };

export type Tag = { id: string, tag_name: string, content: string, created_at: string, updated_at: string, };

export type CreateTag = { tag_name: string, content: string, };

export type UpdateTag = { tag_name: string | null, content: string | null, };

export type DraftFollowUpData = { message: string, executor_config: ExecutorConfig, selected_skills?: Array<SelectedSkill> | null, };

export type DraftWorkspaceData = { message: string, repos: Array<DraftWorkspaceRepo>, directory_path: string | null, executor_config: ExecutorConfig | null, linked_issue: DraftWorkspaceLinkedIssue | null, attachments: Array<DraftWorkspaceAttachment>, };

export type DraftWorkspaceAttachment = { id: string, file_path: string, original_name: string, mime_type: string | null, size_bytes: bigint, };

export type DraftWorkspaceLinkedIssue = { issue_id: string, simple_id: string, title: string, remote_project_id: string, };

export type DraftWorkspaceRepo = { repo_id: string, target_branch: string, };

export type DraftIssueData = { title: string, description: string | null, status_id: string, 
/**
 * Stored as the string value of IssuePriority (e.g. "urgent", "high", "medium", "low")
 */
priority: string | null, assignee_ids: Array<string>, tag_ids: Array<string>, create_draft_workspace: boolean, 
/**
 * The project this draft belongs to
 */
project_id: string, 
/**
 * Parent issue ID if creating a sub-issue
 */
parent_issue_id: string | null, };

export type PreviewSettingsData = { url: string, screen_size: string | null, responsive_width: number | null, responsive_height: number | null, };

export type WorkspaceNotesData = { content: string, };

export type WorkspacePanelStateData = { right_main_panel_mode: string | null, is_left_main_panel_visible: boolean, };

export type WorkspacePrFilterData = "all" | "has_pr" | "no_pr";

export type WorkspaceSortByData = "updated_at" | "created_at";

export type WorkspaceSortOrderData = "asc" | "desc";

export type WorkspaceFilterStateData = { project_ids: Array<string>, pr_filter: WorkspacePrFilterData, };

export type WorkspaceSortStateData = { sort_by: WorkspaceSortByData, sort_order: WorkspaceSortOrderData, };

export type UiPreferencesData = { 
/**
 * Preferred repo actions per repo
 */
repo_actions: { [key in string]?: string }, 
/**
 * Expanded/collapsed state for UI sections
 */
expanded: { [key in string]?: boolean }, 
/**
 * Context bar position
 */
context_bar_position: string | null, 
/**
 * Pane sizes
 */
pane_sizes: { [key in string]?: JsonValue }, 
/**
 * Collapsed paths per workspace in file tree
 */
collapsed_paths: { [key in string]?: Array<string> }, 
/**
 * Preferred file-search repo
 */
file_search_repo_id: string | null, 
/**
 * Global left sidebar visibility
 */
is_left_sidebar_visible: boolean | null, 
/**
 * Global right sidebar visibility
 */
is_right_sidebar_visible: boolean | null, 
/**
 * Global terminal visibility
 */
is_terminal_visible: boolean | null, 
/**
 * Workspace-specific panel states
 */
workspace_panel_states: { [key in string]?: WorkspacePanelStateData }, 
/**
 * Workspace sidebar filter preferences
 */
workspace_filters: WorkspaceFilterStateData, 
/**
 * Workspace sidebar sort preferences
 */
workspace_sort: WorkspaceSortStateData, 
/**
 * Last selected organization ID
 */
selected_org_id: string | null, 
/**
 * Last selected project ID
 */
selected_project_id: string | null, 
/**
 * Default setting for creating a draft workspace from new issues
 */
create_draft_workspace_by_default: boolean | null, 
/**
 * Kanban project view selections (active view per project)
 */
kanban_project_view_selections: { [key in string]?: JsonValue }, 
/**
 * Kanban project view preferences (filters, toggles per project per view)
 */
kanban_project_view_preferences: { [key in string]?: JsonValue }, };

export type ProjectRepoDefaultsData = { repos: Array<DraftWorkspaceRepo>, directory_path: string | null, };

export type ScratchPayload = { "type": "DRAFT_TASK", "data": string } | { "type": "DRAFT_FOLLOW_UP", "data": DraftFollowUpData } | { "type": "DRAFT_WORKSPACE", "data": DraftWorkspaceData } | { "type": "DRAFT_ISSUE", "data": DraftIssueData } | { "type": "PREVIEW_SETTINGS", "data": PreviewSettingsData } | { "type": "WORKSPACE_NOTES", "data": WorkspaceNotesData } | { "type": "UI_PREFERENCES", "data": UiPreferencesData } | { "type": "PROJECT_REPO_DEFAULTS", "data": ProjectRepoDefaultsData };

export enum ScratchType { DRAFT_TASK = "DRAFT_TASK", DRAFT_FOLLOW_UP = "DRAFT_FOLLOW_UP", DRAFT_WORKSPACE = "DRAFT_WORKSPACE", DRAFT_ISSUE = "DRAFT_ISSUE", PREVIEW_SETTINGS = "PREVIEW_SETTINGS", WORKSPACE_NOTES = "WORKSPACE_NOTES", UI_PREFERENCES = "UI_PREFERENCES", PROJECT_REPO_DEFAULTS = "PROJECT_REPO_DEFAULTS" }

export type Scratch = { id: string, payload: ScratchPayload, created_at: string, updated_at: string, };

export type CreateScratch = { payload: ScratchPayload, };

export type UpdateScratch = { payload: ScratchPayload, };

export type Workspace = { id: string, container_ref: string | null, workspace_kind: WorkspaceKind, container_ownership: ContainerOwnership, branch: string, setup_completed_at: string | null, created_at: string, updated_at: string, archived: boolean, pinned: boolean, name: string | null, worktree_deleted: boolean, };

export type WorkspaceKind = "worktree" | "direct_folder";

export type ContainerOwnership = "managed" | "external";

export type WorkspaceWithStatus = { is_running: boolean, is_errored: boolean, id: string, container_ref: string | null, workspace_kind: WorkspaceKind, container_ownership: ContainerOwnership, branch: string, setup_completed_at: string | null, created_at: string, updated_at: string, archived: boolean, pinned: boolean, name: string | null, worktree_deleted: boolean, };

export type ArenaGroup = { id: string, task_id: string, prompt: string, base_branch: string, mode: ArenaMode, lifecycle_status: ArenaLifecycleStatus, winner_candidate_id: string | null, promoted_at: string | null, closed_at: string | null, created_at: string, updated_at: string, };

export type ArenaStatus = "active" | "promoted" | "archived";

export type ArenaMode = "design" | "implementation";

export type ArenaLifecycleStatus = "open" | "closed" | "adopted" | "implementation_started";

export type ArenaCandidatePurpose = "attempt" | "synthesis";

export type ArenaCandidate = { id: string, arena_group_id: string, workspace_id: string, purpose: ArenaCandidatePurpose, sort_order: bigint, created_at: string, updated_at: string, };

export type TaskExecutionKind = "agent" | "workflow" | "arena";

export type TaskStatus = "draft" | "pending" | "running" | "waiting" | "succeeded" | "failed" | "cancelled";

export type TaskOpenTarget = { "kind": "agent", session_id: string, workspace_id: string, } | { "kind": "workflow", attempt_id: string, workflow_id: string, latest_run_id: string | null, } | { "kind": "arena", arena_group_id: string, };

export type Task = { id: string, project_id: string, issue_id: string, parent_task_id: string | null, title: string, execution_kind: TaskExecutionKind, created_at: string, updated_at: string, };

export type TaskSummary = { id: string, project_id: string, issue_id: string, parent_task_id: string | null, title: string, execution_kind: TaskExecutionKind, status: TaskStatus, open_target: TaskOpenTarget, created_at: string, updated_at: string, };

export type TaskCursor = { updated_at: string, id: string, };

export type TaskSummaryPage = { tasks: Array<TaskSummary>, next_cursor: TaskCursor | null, };

export type SessionListItem = { id: string, workspace_id: string, task_id: string, project_id: string, issue_id: string, title: string, executor: string | null, created_at: string, updated_at: string, };

export type SessionCursor = { updated_at: string, id: string, };

export type SessionPage = { sessions: Array<SessionListItem>, next_cursor: SessionCursor | null, };

export type ExecutionDataOwner = "local_host";

export type ExecutionDataCapabilities = { owner: ExecutionDataOwner, task_queries: boolean, execution_actions: boolean, };

export type WorkflowSource = "system" | "project";

export type WorkflowRunStatus = "pending" | "running" | "awaiting_human" | "awaiting_arena" | "cancelling" | "succeeded" | "failed" | "canceled";

export type WorkflowAttemptStatus = "draft" | "ready" | "running" | "awaiting_human" | "awaiting_arena" | "cancelling" | "succeeded" | "failed" | "canceled";

export type NodeExecutionStatus = "pending" | "running" | "awaiting_human" | "awaiting_arena" | "cancelling" | "succeeded" | "failed" | "cancelled" | "skipped";

export type Workflow = { id: string, source: WorkflowSource, project_id: string | null, name: string, description: string | null, graph_json: string, revision: bigint, created_at: string, updated_at: string, };

export type WorkflowRun = { id: string, orchestration_run_id: string | null, workflow_id: string, attempt_id: string | null, issue_id: string, workspace_id: string | null, trigger_source: string, input_text: string, output_text: string | null, status: WorkflowRunStatus, started_at: string | null, finished_at: string | null, error_text: string | null, created_at: string, updated_at: string, };

export type WorkflowAttempt = { id: string, task_id: string, workflow_id: string, latest_run_id: string | null, workspace_id: string | null, status: WorkflowAttemptStatus, created_at: string, updated_at: string, };

export type NodeExecution = { id: string, run_id: string, task_id: string | null, node_id: string, node_type: string, iteration: bigint, status: NodeExecutionStatus, input_text: string | null, output_text: string | null, session_id: string | null, orchestration_node_execution_id: string | null, agent_run_id: string | null, execution_process_id: string | null, arena_group_id: string | null, tokens_used: bigint | null, cost_estimate: number | null, started_at: string | null, finished_at: string | null, error_text: string | null, created_at: string, updated_at: string, };

export type CreateWorkflow = { source: WorkflowSource, project_id: string | null, name: string, description: string | null, graph_json: string, };

export type UpdateWorkflow = { expected_revision: bigint, name: string | null, description: string | null, graph_json: string | null, };

export type CreateWorkflowRun = { workflow_id: string, attempt_id: string | null, issue_id: string, workspace_id: string | null, trigger_source: string, input_text: string, };

export type CreateWorkflowAttempt = { id: string, task_id: string, workflow_id: string, };

export type UpdateWorkflowAttemptRuntime = { latest_run_id: string | null, workspace_id: string | null, status: WorkflowAttemptStatus, };

export type UpdateWorkflowRunStatus = { status: WorkflowRunStatus, output_text: string | null, error_text: string | null, };

export type CreateNodeExecution = { run_id: string, task_id: string | null, node_id: string, node_type: string, iteration: bigint, status: NodeExecutionStatus, input_text: string | null, };

export type UpdateNodeExecution = { status: NodeExecutionStatus, input_text: string | null, output_text: string | null, session_id: string | null, orchestration_node_execution_id: string | null, agent_run_id: string | null, execution_process_id: string | null, arena_group_id: string | null, tokens_used: bigint | null, cost_estimate: number | null, error_text: string | null, };

export type ArenaAttemptInput = { executor_config: ExecutorConfig, name?: string | null, 
/**
 * Optional per-attempt prompt override. Falls back to the
 * group-level `prompt` when not provided.
 */
prompt?: string | null, };

export type CreateArenaRequest = { project_id: string, base_branch: string, prompt: string, mode: ArenaMode, repos: Array<WorkspaceRepoInput>, attempts: Array<ArenaAttemptInput>, };

export type ArenaWorkspaceSummary = { candidate_id: string, workspace_id: string, session_id: string | null, name: string | null, branch: string, purpose: ArenaCandidatePurpose, arena_status: ArenaStatus, executor: string | null, variant: string | null, latest_agent_run_status: AgentRunStatus | null, has_uncommitted_changes: boolean | null, };

export type ArenaEventKind = "ask_all" | "workspace" | "challenge" | "synthesize" | "start_implementation";

export type ArenaEvent = { id: string, arena_group_id: string, kind: ArenaEventKind, prompt: string, source_workspace_id: string | null, target_workspace_id: string | null, synthesis_workspace_id: string | null, created_at: string, };

export type ArenaGroupResponse = { workspaces: Array<ArenaWorkspaceSummary>, events: Array<ArenaEvent>, id: string, task_id: string, prompt: string, base_branch: string, mode: ArenaMode, lifecycle_status: ArenaLifecycleStatus, winner_candidate_id: string | null, promoted_at: string | null, closed_at: string | null, created_at: string, updated_at: string, };

export type PromoteArenaRequest = { candidate_id: string, };

export type RetryArenaRequest = { executor_config: ExecutorConfig, name?: string | null, 
/**
 * Optional override; falls back to the group's prompt.
 */
prompt?: string | null, };

export type DissolveArenaResponse = { group_id: string, workspaces_archived: number, };

export type CloseArenaResponse = { group_id: string, lifecycle_status: ArenaLifecycleStatus, };

export type StartArenaImplementationRequest = { candidate_id: string, follow_up_prompt?: string | null, executor_config?: ExecutorConfig | null, };

export type ArenaSynthesizeOptions = { include_original_prompt: boolean, include_attempt_summaries: boolean, include_activity: boolean, };

export type ArenaMessageTarget = { "type": "all" } | { "type": "workspace", workspace_id: string, } | { "type": "challenge", responder_workspace_id: string, source_workspace_id: string, } | { "type": "synthesize", options: ArenaSynthesizeOptions, };

export type ArenaWorkspaceExecutorConfig = { workspace_id: string, executor_config: ExecutorConfig, };

export type ArenaMessageRequest = { target: ArenaMessageTarget, prompt: string, executor_config: ExecutorConfig, executor_configs: Array<ArenaWorkspaceExecutorConfig>, };

export type WorkflowTemplateResponse = { id: string, source: WorkflowSource, project_id: string | null, name: string, description: string | null, graph_json: string, revision: number, created_at: string, updated_at: string, };

export type WorkflowTemplateListResponse = { workflows: Array<WorkflowTemplateResponse>, };

export type CreateWorkflowRequest = { name: string, description: string | null, graph_json: string, };

export type UpdateWorkflowRequest = { expected_revision: number, name: string | null, description: string | null, graph_json: string | null, };

export type WorkflowRevisionConflict = { workflow_id: string, expected_revision: number, current_revision: number, };

export type TriggerWorkflowRequest = { issue_id: string, workspace_id: string | null, trigger_source: string, input_text: string, };

export type CreateWorkflowAttemptRequest = { name: string | null, graph_json: string, repos?: Array<DraftWorkspaceRepo>, };

export type RunWorkflowAttemptRequest = { workspace_id: string | null, trigger_source: string, input_text: string, repos?: Array<DraftWorkspaceRepo>, };

export type SelectArenaWinnerRequest = { candidate_id: string, };

export type SelectConditionBranchRequest = { selected_target_node_ids: Array<string>, reason?: string, };

export type WorkflowAttemptResponse = { id: string, project_id: string, issue_id: string, workflow_id: string, latest_run_id: string | null, workspace_id: string | null, name: string, status: WorkflowAttemptStatus, created_at: string, updated_at: string, };

export type WorkflowAttemptListResponse = { attempts: Array<WorkflowAttemptResponse>, };

export type WorkflowRuntimeHealth = "ok" | "starting" | "slow" | "projection_degraded" | "unknown";

export type WorkflowNodeWorkStatus = "pending" | "starting" | "running" | "awaiting_human" | "awaiting_arena" | "cancelling" | "succeeded" | "failed" | "cancelled" | "skipped";

export type WorkflowNodeWorkView = { node_id: string, node_type: string, iteration: bigint, status: WorkflowNodeWorkStatus, pending_work_count: number, starting_child_count: number, active_execution_id: string | null, active_session_id: string | null, orchestration_node_execution_id: string | null, active_agent_run_id: string | null, projection_status: ProjectionStatus | null, active_started_at: string | null, active_elapsed_ms: number | null, active_slow: boolean, active_slow_threshold_ms: number, runtime_health: WorkflowRuntimeHealth, can_open_session: boolean, can_retry: boolean, can_approve: boolean, can_reject: boolean, can_select_arena_winner: boolean, can_select_condition_branch: boolean, can_cancel_node: boolean, };

export type WorkflowRunRuntimeView = { run_id: string, status: WorkflowRunStatus, active_node_count: number, pending_node_count: number, waiting_node_count: number, failed_node_count: number, completed_node_count: number, node_work: Array<WorkflowNodeWorkView>, };

export type WorkflowRunResponse = { id: string, orchestration_run_id: string | null, workflow_id: string, attempt_id: string | null, issue_id: string, workspace_id: string | null, trigger_source: string, input_text: string, output_text: string | null, status: WorkflowRunStatus, started_at: string | null, finished_at: string | null, error_text: string | null, created_at: string, updated_at: string, nodes: Array<WorkflowNodeExecutionResponse>, runtime_view?: WorkflowRunRuntimeView, };

export type WorkflowNodeExecutionResponse = { id: string, run_id: string, task_id: string | null, node_id: string, node_type: string, iteration: bigint, status: NodeExecutionStatus, input_text: string | null, output_text: string | null, session_id: string | null, orchestration_node_execution_id: string | null, agent_run_id: string | null, projection_status: ProjectionStatus | null, execution_process_id: string | null, arena_group_id: string | null, tokens_used: bigint | null, cost_estimate: number | null, started_at: string | null, finished_at: string | null, error_text: string | null, created_at: string, updated_at: string, };

export type WorkflowActionResponse = { run_id: string, node_id: string | null, status: WorkflowRunStatus, };

export type ScheduledTaskTargetType = "workflow";

export type ScheduledTaskKind = "daily" | "weekly";

export type ScheduledTaskConcurrencyPolicy = "skip_if_running";

export type ScheduledTaskLastStatus = "idle" | "running" | "awaiting_human" | "awaiting_arena" | "succeeded" | "failed" | "skipped" | "canceled";

export type ScheduledTaskResponse = { id: string, project_id: string, target_type: ScheduledTaskTargetType, target_id: string, context_issue_id: string, name: string | null, enabled: boolean, schedule_kind: ScheduledTaskKind, time_of_day: string, weekday: number | null, timezone: string, input_text: string, concurrency_policy: ScheduledTaskConcurrencyPolicy, last_run_id: string | null, last_status: ScheduledTaskLastStatus, last_error: string | null, last_triggered_at: string | null, next_run_at: string | null, created_at: string, updated_at: string, };

export type ScheduledTaskListResponse = { tasks: Array<ScheduledTaskResponse>, };

export type ListScheduledTasksQuery = { target_type?: ScheduledTaskTargetType, target_id?: string, };

export type UpsertScheduledTaskRequest = { target_type: ScheduledTaskTargetType, target_id: string, context_issue_id: string, name?: string, enabled: boolean, schedule_kind: ScheduledTaskKind, time_of_day: string, weekday?: number, timezone: string, input_text: string, };

export type UpdateScheduledTaskRequest = { context_issue_id?: string, name?: string, enabled?: boolean, schedule_kind?: ScheduledTaskKind, time_of_day?: string, weekday?: number, timezone?: string, input_text?: string, };

export type ScheduledTaskRunNowResponse = { task: ScheduledTaskResponse, run?: WorkflowRunResponse, skipped: boolean, };

export type Session = { id: string, workspace_id: string, name: string | null, executor: string | null, agent_working_dir: string | null, created_at: string, updated_at: string, };

export type ExecutionProcess = { id: string, session_id: string, run_reason: ExecutionProcessRunReason, executor_action: ExecutorAction, status: ExecutionProcessStatus, exit_code: bigint | null, 
/**
 * dropped: true if this process is excluded from the current
 * history view (due to restore/trimming). Hidden from logs/timeline;
 * still listed in the Processes tab.
 */
dropped: boolean, started_at: string, completed_at: string | null, created_at: string, updated_at: string, };

export enum ExecutionProcessStatus { running = "running", completed = "completed", failed = "failed", killed = "killed" }

export type ExecutionProcessRunReason = "setupscript" | "cleanupscript" | "archivescript" | "devserver";

export type ExecutionProcessRepoState = { id: string, execution_process_id: string, repo_id: string, before_head_commit: string | null, after_head_commit: string | null, merge_commit: string | null, created_at: Date, updated_at: Date, };

export type Merge = { "type": "direct" } & DirectMerge | { "type": "pr" } & PrMerge;

export type DirectMerge = { id: string, workspace_id: string, repo_id: string, merge_commit: string, target_branch_name: string, created_at: string, };

export type PrMerge = { id: string, workspace_id: string, repo_id: string, created_at: string, target_branch_name: string, pr_info: PullRequestInfo, };

export type MergeStatus = "open" | "merged" | "closed" | "unknown";

export type PullRequestInfo = { number: bigint, url: string, status: MergeStatus, merged_at: string | null, merge_commit_sha: string | null, };

export type ApprovalInfo = { approval_id: string, tool_name: string, execution_process_id: string, is_question: boolean, created_at: string, timeout_at: string, };

export type ApprovalStatus = { "status": "pending" } | { "status": "approved" } | { "status": "denied", reason?: string, } | { "status": "timed_out" };

export type QuestionAnswer = { question: string, answer: Array<string>, };

export type QuestionStatus = { "status": "answered", answers: Array<QuestionAnswer>, } | { "status": "timed_out" };

export type ApprovalOutcome = { "status": "approved" } | { "status": "denied", reason?: string, } | { "status": "answered", answers: Array<QuestionAnswer>, } | { "status": "timed_out" };

export type ApprovalResponse = { execution_process_id: string, status: ApprovalOutcome, };

export type Diff = { change: DiffChangeKind, oldPath: string | null, newPath: string | null, oldContent: string | null, newContent: string | null, 
/**
 * True when file contents are intentionally omitted (e.g., too large)
 */
contentOmitted: boolean, 
/**
 * Optional precomputed stats for omitted content
 */
additions: number | null, deletions: number | null, repoId: string | null, };

export type DiffChangeKind = "added" | "deleted" | "modified" | "renamed" | "copied" | "permissionChange";

export type ApiResponse<T, E = T> = { success: boolean, data: T | null, error_data: E | null, message: string | null, };

export type LoginStatus = { "status": "loggedout" } | { "status": "loggedin", profile: ProfileResponse | null, };

export type ProfileResponse = { user_id: string, username: string | null, email: string, providers: Array<ProviderProfile>, };

export type ProviderProfile = { provider: string, username: string | null, display_name: string | null, email: string | null, avatar_url: string | null, };

export type StatusResponse = { logged_in: boolean, profile: ProfileResponse | null, degraded: boolean | null, };

export enum MemberRole { ADMIN = "ADMIN", MEMBER = "MEMBER" }

export enum InvitationStatus { PENDING = "PENDING", ACCEPTED = "ACCEPTED", DECLINED = "DECLINED", EXPIRED = "EXPIRED" }

export type Organization = { id: string, name: string, slug: string, is_personal: boolean, issue_prefix: string, created_at: string, updated_at: string, };

export type OrganizationWithRole = { id: string, name: string, slug: string, is_personal: boolean, issue_prefix: string, created_at: string, updated_at: string, user_role: MemberRole, };

export type ListOrganizationsResponse = { organizations: Array<OrganizationWithRole>, };

export type GetOrganizationResponse = { organization: Organization, user_role: string, };

export type CreateOrganizationRequest = { name: string, slug: string, };

export type CreateOrganizationResponse = { organization: OrganizationWithRole, };

export type UpdateOrganizationRequest = { name: string, };

export type Invitation = { id: string, organization_id: string, invited_by_user_id: string | null, email: string, role: MemberRole, status: InvitationStatus, token: string, created_at: string, expires_at: string, };

export type CreateInvitationRequest = { email: string, role: MemberRole, };

export type CreateInvitationResponse = { invitation: Invitation, };

export type ListInvitationsResponse = { invitations: Array<Invitation>, };

export type GetInvitationResponse = { id: string, organization_slug: string, role: MemberRole, expires_at: string, };

export type AcceptInvitationResponse = { organization_id: string, organization_slug: string, role: MemberRole, };

export type RevokeInvitationRequest = { invitation_id: string, };

export type OrganizationMemberInfo = { user_id: string, role: MemberRole, joined_at: string, };

export type OrganizationMemberWithProfile = { user_id: string, role: MemberRole, joined_at: string, first_name: string | null, last_name: string | null, username: string | null, email: string | null, avatar_url: string | null, };

export type ListMembersResponse = { members: Array<OrganizationMemberWithProfile>, };

export type UpdateMemberRoleRequest = { role: MemberRole, };

export type UpdateMemberRoleResponse = { user_id: string, role: MemberRole, };

export type RegisterRepoRequest = { path: string, display_name: string | null, };

export type InitRepoRequest = { parent_path: string, folder_name: string, };

export type TagSearchParams = { search: string | null, };

export type TokenResponse = { access_token: string, expires_at: string | null, };

export type UserSystemInfo = { version: string, config: Config, machine_id: string, login_status: LoginStatus, remote_auth_degraded: string | null, environment: Environment, 
/**
 * Capabilities supported per executor (e.g., { "CLAUDE_CODE": ["SESSION_FORK"] })
 */
capabilities: { [key in string]?: Array<BaseAgentCapability> }, shared_api_base: string | null, preview_proxy_port: number | null, executors: { [key in BaseCodingAgent]?: ExecutorProfile }, };

export type Environment = { os_type: string, os_version: string, os_architecture: string, bitness: string, };

export type McpServerQuery = { executor: BaseCodingAgent, };

export type UpdateMcpServersBody = { servers: { [key in string]?: JsonValue }, };

export type GetMcpServerResponse = { mcp_config: McpConfig, config_path: string, };

export type CheckEditorAvailabilityQuery = { editor_type: EditorType, };

export type CheckEditorAvailabilityResponse = { available: boolean, };

export type CheckAgentAvailabilityQuery = { executor: BaseCodingAgent, };

export type AgentGarageEntry = { executor: BaseCodingAgent, availability: AvailabilityInfo, capabilities: Array<BaseAgentCapability>, 
/**
 * Version of the binary bundled by the npx wrapper (pin & ship), when known.
 */
bundled_version?: string, policy?: AgentProviderPolicy, };

export type AgentPresetOptionsQuery = { executor: BaseCodingAgent, variant: string | null, };

export type CurrentUserResponse = { user_id: string, };

export type StartSpake2EnrollmentRequest = { enrollment_code: string, client_message_b64: string, };

export type FinishSpake2EnrollmentRequest = { enrollment_id: string, client_id: string, client_name: string, client_browser: string, client_os: string, client_device: string, public_key_b64: string, client_proof_b64: string, };

export type StartSpake2EnrollmentResponse = { enrollment_id: string, server_message_b64: string, };

export type FinishSpake2EnrollmentResponse = { signing_session_id: string, server_public_key_b64: string, server_proof_b64: string, };

export type RelayPairedClient = { client_id: string, client_name: string, client_browser: string, client_os: string, client_device: string, };

export type ListRelayPairedClientsResponse = { clients: Array<RelayPairedClient>, };

export type RemoveRelayPairedClientResponse = { removed: boolean, };

export type RefreshRelaySigningSessionRequest = { client_id: string, timestamp: bigint, nonce: string, signature_b64: string, };

export type RefreshRelaySigningSessionResponse = { signing_session_id: string, };

export type ResumableAgentSession = { agent_session_id: string, title: string, last_used_at: string, };

export type NativeSessionDiscoveryState = "supported" | "unsupported";

export type NativeSessionPreviewEntry = { role: string, content: string, timestamp?: string, };

export type NativeAgentSessionPreview = { agent_session_id: string, title: string, last_used_at?: string, entries: Array<NativeSessionPreviewEntry>, truncated: boolean, turn_limit: number, };

export type CreateFollowUpAttempt = { prompt: string, selected_skills?: Array<SelectedSkill>, executor_config: ExecutorConfig, resume_session_id?: string, resume_scope_path?: string, };

export type ChangeTargetBranchRequest = { repo_id: string, new_target_branch: string, };

export type ChangeTargetBranchResponse = { repo_id: string, new_target_branch: string, status: [number, number], };

export type AddWorkspaceRepoRequest = { repo_id: string, target_branch: string, };

export type AddWorkspaceRepoResponse = { workspace: Workspace, repo: RepoWithTargetBranch, };

export type MergeWorkspaceRequest = { repo_id: string, };

export type PushWorkspaceRequest = { repo_id: string, };

export type RenameBranchRequest = { new_branch_name: string, };

export type RenameBranchResponse = { branch: string, };

export type StartReviewRequest = { executor_config: ExecutorConfig, additional_prompt: string | null, use_all_workspace_commits: boolean, };

export type ReviewError = { "type": "process_already_running" };

export type OpenEditorRequest = { editor_type: string | null, file_path: string | null, };

export type OpenEditorResponse = { url: string | null, };

export type OpenRemoteEditorResponse = { url: string, local_port: number, ssh_alias: string, };

export type OpenRemoteWorkspaceInEditorRequest = { host_id: string, workspace_id: string, editor_type: string | null, file_path: string | null, };

export type PairRelayHostRequest = { host_id: string, host_name: string, enrollment_code: string, };

export type PairRelayHostResponse = { paired: boolean, };

export type RelayPairedHost = { host_id: string, host_name: string | null, paired_at: string | null, };

export type ListRelayPairedHostsResponse = { hosts: Array<RelayPairedHost>, };

export type RemoveRelayPairedHostResponse = { removed: boolean, };

export type CreateWorkspaceApiRequest = { name: string | null, };

export type LinkedIssueInfo = { remote_project_id: string, issue_id: string, };

export type CreateWorkspaceMode = "worktree" | "direct_folder";

export type CreatePrApiRequest = { title: string, body: string | null, target_branch: string | null, draft: boolean | null, repo_id: string, auto_generate_description: boolean, };

export type AttachmentResponse = { id: string, file_path: string, original_name: string, mime_type: string | null, size_bytes: bigint, hash: string, created_at: string, updated_at: string, };

export type AttachmentMetadata = { exists: boolean, file_name: string | null, path: string | null, size_bytes: bigint | null, format: string | null, proxy_url: string | null, };

export type WorkspaceFileKind = "file" | "directory";

export type WorkspaceFileEntry = { workspace_id: string, repo_id: string, repo_name: string, path: string, name: string, kind: WorkspaceFileKind, size_bytes: bigint | null, modified_at: string | null, mime_type: string | null, is_binary: boolean | null, };

export type WorkspaceFileRepoNode = { workspace_id: string, repo_id: string, repo_name: string, repo_display_name: string, entries: Array<WorkspaceFileEntry>, truncated: boolean, };

export type WorkspaceFileTreeResponse = { repos: Array<WorkspaceFileRepoNode>, };

export type WorkspaceFileDirectoryResponse = { workspace_id: string, repo_id: string, repo_name: string, path: string, entries: Array<WorkspaceFileEntry>, truncated: boolean, };

export type WorkspaceFileContentKind = "text" | "image" | "binary" | "unsupported";

export type WorkspaceFileContent = { workspace_id: string, repo_id: string, repo_name: string, path: string, name: string, kind: WorkspaceFileContentKind, mime_type: string | null, language: string | null, content: string | null, raw_url: string | null, size_bytes: bigint, truncated: boolean, };

export type WorkspaceRepoInput = { repo_id: string, target_branch: string, };

export type RunAgentSetupRequest = { executor_profile_id: ExecutorProfileId, };

export type RunAgentSetupResponse = Record<string, never>;

export type GhCliSetupError = "BREW_MISSING" | "SETUP_HELPER_NOT_SUPPORTED" | { "OTHER": { message: string, } };

export type RebaseWorkspaceRequest = { repo_id: string, old_base_branch: string | null, new_base_branch: string | null, };

export type ContinueRebaseRequest = { repo_id: string, };

export type AbortConflictsRequest = { repo_id: string, };

export type GitOperationError = { "type": "merge_conflicts", message: string, op: ConflictOp, conflicted_files: Array<string>, target_branch: string, } | { "type": "rebase_in_progress" };

export type PushError = { "type": "force_push_required" };

export type PrError = { "type": "cli_not_installed", provider: ProviderKind, } | { "type": "cli_not_logged_in", provider: ProviderKind, } | { "type": "git_cli_not_logged_in" } | { "type": "git_cli_not_installed" } | { "type": "target_branch_not_found", branch: string, } | { "type": "unsupported_provider" };

export type RunScriptError = { "type": "no_script_configured" } | { "type": "process_already_running" };

export type AssociateWorkspaceAttachmentsRequest = { attachment_ids: Array<string>, };

export type ImportIssueAttachmentsRequest = { issue_id: string, };

export type ImportIssueAttachmentsResponse = { attachment_ids: Array<string>, };

export type AttachPrResponse = { pr_attached: boolean, pr_url: string | null, pr_number: bigint | null, pr_status: MergeStatus | null, };

export type AttachExistingPrRequest = { repo_id: string, };

export type PrCommentsResponse = { comments: Array<UnifiedPrComment>, };

export type GetPrCommentsError = { "type": "no_pr_attached" } | { "type": "cli_not_installed", provider: ProviderKind, } | { "type": "cli_not_logged_in", provider: ProviderKind, };

export type GetPrCommentsQuery = { repo_id: string, };

export type CreateAndStartWorkspaceRequest = { mode: CreateWorkspaceMode, name: string | null, repos: Array<WorkspaceRepoInput>, directory_path?: string, linked_issue: LinkedIssueInfo | null, executor_config: ExecutorConfig, prompt: string, selected_skills?: Array<SelectedSkill>, resume_session_id?: string, resume_scope_path?: string, attachment_ids: Array<string> | null, };

export type CreateAndStartWorkspaceResponse = { workspace: Workspace, agent_run: AgentRunPortSnapshot, };

export type UnifiedPrComment = { "comment_type": "general", id: string, author: string, author_association: string | null, body: string, created_at: string, url: string | null, } | { "comment_type": "review", id: bigint, author: string, author_association: string | null, body: string, created_at: string, url: string | null, path: string, line: bigint | null, side: string | null, diff_hunk: string | null, };

export type ProviderKind = "git_hub" | "azure_dev_ops" | "unknown";

export type PullRequestDetail = { number: bigint, url: string, status: MergeStatus, merged_at: string | null, merge_commit_sha: string | null, title: string, base_branch: string, head_branch: string, };

export type GitRemote = { name: string, url: string, };

export type ListPrsError = { "type": "cli_not_installed", provider: ProviderKind, } | { "type": "auth_failed", message: string, } | { "type": "unsupported_provider" };

export type LinkPrToIssueRequest = { pr_url: string, pr_number: number, base_branch: string, };

export type CreateWorkspaceFromPrBody = { repo_id: string, pr_number: bigint, pr_title: string, pr_url: string, head_branch: string, base_branch: string, run_setup: boolean, remote_name: string | null, };

export type CreateWorkspaceFromPrResponse = { workspace: Workspace, };

export type CreateFromPrError = { "type": "pr_not_found" } | { "type": "branch_fetch_failed", message: string, } | { "type": "cli_not_installed", provider: ProviderKind, } | { "type": "auth_failed", message: string, } | { "type": "unsupported_provider" };

export type RepoBranchStatus = { repo_id: string, repo_name: string, commits_behind: number | null, commits_ahead: number | null, has_uncommitted_changes: boolean | null, head_oid: string | null, uncommitted_count: number | null, untracked_count: number | null, target_branch_name: string, remote_commits_behind: number | null, remote_commits_ahead: number | null, merges: Array<Merge>, is_rebase_in_progress: boolean, conflict_op: ConflictOp | null, conflicted_files: Array<string>, is_target_remote: boolean, };

export type UpdateWorkspace = { archived: boolean | null, pinned: boolean | null, name: string | null, };

export type UpdateSession = { name: string | null, };

export type WorkspaceSummaryRequest = { archived: boolean, };

export type WorkspaceSummary = { workspace_id: string, 
/**
 * Session ID of the latest canonical AgentRun
 */
latest_session_id: string | null, 
/**
 * Is a tool approval currently pending?
 */
has_pending_approval: boolean, 
/**
 * Number of files with changes
 */
files_changed: number | null, 
/**
 * Total lines added across all files
 */
lines_added: number | null, 
/**
 * Total lines removed across all files
 */
lines_removed: number | null, 
/**
 * When the latest canonical AgentRun reached its current terminal state
 */
latest_process_completed_at?: string, 
/**
 * Status of the latest canonical AgentRun
 */
latest_process_status: AgentRunStatus | null, 
/**
 * Is a dev server currently running?
 */
has_running_dev_server: boolean, 
/**
 * Does this workspace have unseen canonical AgentRuns?
 */
has_unseen_turns: boolean, 
/**
 * PR status for this workspace (if any PR exists)
 */
pr_status: MergeStatus | null, 
/**
 * PR number for this workspace (if any PR exists)
 */
pr_number: bigint | null, 
/**
 * PR URL for this workspace (if any PR exists)
 */
pr_url: string | null, };

export type WorkspaceSummaryResponse = { summaries: Array<WorkspaceSummary>, };

export type DiffStats = { files_changed: number, lines_added: number, lines_removed: number, };

export type DirectoryEntry = { name: string, path: string, is_directory: boolean, is_git_repo: boolean, last_modified: bigint | null, };

export type DirectoryListResponse = { entries: Array<DirectoryEntry>, current_path: string, };

export type PickFolderRequest = { initial_path: string | null, title: string | null, };

export type InspectDirectoryRequest = { path: string, };

export type DirectoryInspection = { path: string, is_git_repo: boolean, repo: Repo | null, current_branch: string | null, };

export type SearchMode = "taskform" | "settings";

export type Config = { config_version: string, theme: ThemeMode, executor_profile: ExecutorProfileId, disclaimer_acknowledged: boolean, onboarding_acknowledged: boolean, remote_onboarding_acknowledged: boolean, notifications: NotificationConfig, editor: EditorConfig, github: GitHubConfig, analytics_enabled: boolean, workspace_dir: string | null, last_app_version: string | null, show_release_notes: boolean, language: UiLanguage, git_branch_prefix: string, showcases: ShowcaseState, pr_auto_description_enabled: boolean, pr_auto_description_prompt: string | null, commit_reminder_enabled: boolean, commit_reminder_prompt: string | null, send_message_shortcut: SendMessageShortcut, relay_enabled: boolean, host_nickname: string | null, hidden_agents: Array<BaseCodingAgent>, };

export type NotificationConfig = { sound_enabled: boolean, push_enabled: boolean, sound_file: SoundFile, };

export enum ThemeMode { LIGHT = "LIGHT", DARK = "DARK", SYSTEM = "SYSTEM" }

export type EditorConfig = { editor_type: EditorType, custom_command: string | null, remote_ssh_host: string | null, remote_ssh_user: string | null, auto_install_extension: boolean, };

export enum EditorType { VS_CODE = "VS_CODE", VS_CODE_INSIDERS = "VS_CODE_INSIDERS", CURSOR = "CURSOR", WINDSURF = "WINDSURF", INTELLI_J = "INTELLI_J", ZED = "ZED", XCODE = "XCODE", GOOGLE_ANTIGRAVITY = "GOOGLE_ANTIGRAVITY", CUSTOM = "CUSTOM" }

export type EditorOpenError = { "type": "executable_not_found", executable: string, editor_type: EditorType, } | { "type": "invalid_command", details: string, editor_type: EditorType, } | { "type": "launch_failed", executable: string, details: string, editor_type: EditorType, };

export type GitHubConfig = { pat: string | null, oauth_token: string | null, username: string | null, primary_email: string | null, default_pr_base: string | null, };

export enum SoundFile { ABSTRACT_SOUND1 = "ABSTRACT_SOUND1", ABSTRACT_SOUND2 = "ABSTRACT_SOUND2", ABSTRACT_SOUND3 = "ABSTRACT_SOUND3", ABSTRACT_SOUND4 = "ABSTRACT_SOUND4", COW_MOOING = "COW_MOOING", FAHHHHH = "FAHHHHH", PHONE_VIBRATION = "PHONE_VIBRATION", ROOSTER = "ROOSTER" }

export type UiLanguage = "BROWSER" | "EN" | "FR" | "JA" | "ES" | "KO" | "ZH_HANS" | "ZH_HANT";

export type ShowcaseState = { seen_features: Array<string>, };

export type SendMessageShortcut = "ModifierEnter" | "Enter";

export type GitBranch = { name: string, is_current: boolean, is_remote: boolean, last_commit_date: Date, };

export type QueuedMessage = { 
/**
 * The session this message is queued for
 */
session_id: string, 
/**
 * The follow-up data (message + variant)
 */
data: DraftFollowUpData, 
/**
 * Timestamp when the message was queued
 */
queued_at: string, };

export type QueueStatus = { "status": "empty" } | { "status": "queued", message: QueuedMessage, };

export type ConflictOp = "rebase" | "merge" | "cherry_pick" | "revert";

export type ExecutorAction = { typ: ExecutorActionType, next_action: ExecutorAction | null, };

export type SelectedSkill = { name: string, path: string, };

export type McpConfig = { servers: { [key in string]?: JsonValue }, servers_path: Array<string>, template: JsonValue, preconfigured: JsonValue, is_toml_config: boolean, };

export enum AgentSettingsProvider { codex = "codex", claude_code = "claude_code", gemini = "gemini", oh_my_pi = "oh_my_pi" }

export enum SettingScope { user = "user", project = "project" }

export enum SettingSection { general = "general", permissions_sandbox = "permissions_sandbox", instructions = "instructions", environment = "environment", provider_settings = "provider_settings" }

export enum SettingValueType { string = "string", boolean = "boolean", number = "number", string_list = "string_list", string_map = "string_map", json = "json" }

export enum SettingControl { text = "text", textarea = "textarea", toggle = "toggle", select = "select", number = "number", string_list = "string_list", key_value = "key_value", json = "json" }

export enum SettingActivation { immediate = "immediate", next_session = "next_session", explicit_restart = "explicit_restart" }

export enum NativeConfigFormat { toml = "toml", json = "json", jsonc = "jsonc", yaml = "yaml", dotenv = "dotenv", text = "text", opaque = "opaque" }

export enum NativeParseStatus { missing = "missing", parsed = "parsed", invalid = "invalid", unsupported = "unsupported" }

export type SettingKey = { namespace: string, name: string, };

export type SettingOption = { value: JsonValue, label: string, description?: string | null, };

export type SettingValidation = { minimum?: number | null, maximum?: number | null, pattern?: string | null, max_length?: number | null, };

export type SettingCapabilities = { readable: boolean, writable: boolean, resettable: boolean, profile_storable: boolean, run_override: boolean, };

export type NativeSettingLocation = { file_id: string, scope: SettingScope, native_path: Array<string>, };

export type SettingDescriptor = { key: SettingKey, section: SettingSection, label: string, description: string, value_type: SettingValueType, control: SettingControl, options: Array<SettingOption>, validation: SettingValidation, supported_scopes: Array<SettingScope>, capabilities: SettingCapabilities, native_locations: Array<NativeSettingLocation>, activation: SettingActivation, };

export type SettingsCapabilities = { readable: boolean, native_writable: boolean, profile_storage: boolean, per_run_overrides: boolean, raw_editable: boolean, };

export type NativeConfigFile = { id: string, path: string, format: NativeConfigFormat, scope: SettingScope, exists: boolean, parse_status: NativeParseStatus, revision?: string | null, writable: boolean, raw_editable: boolean, raw_content?: string | null, error?: string | null, };

export type SettingSourceValue = { source: string, scope: SettingScope, file_id: string, value: JsonValue, revision: string, };

export type EffectiveSetting = { key: SettingKey, sources: Array<SettingSourceValue>, effective_value?: JsonValue | null, effective_source?: string | null, warnings: Array<string>, };

export type UnknownNativeNode = { file_id: string, native_path: string, value: JsonValue, };

export type AgentSettingIssue = { message: string, file_id?: string | null, setting_key?: string | null, recovery: string, };

export type SettingsSnapshot = { provider: AgentSettingsProvider, installed: boolean, provider_version?: string | null, executable_path?: string | null, schema_revision: string, capabilities: SettingsCapabilities, descriptors: Array<SettingDescriptor>, native_files: Array<NativeConfigFile>, effective_settings: Array<EffectiveSetting>, unknown_native_nodes: Array<UnknownNativeNode>, limitations: Array<string>, errors: Array<AgentSettingIssue>, };

export type AgentSettingsProviderError = { provider: AgentSettingsProvider, message: string, };

export type AgentSettingsInventory = { providers: Array<SettingsSnapshot>, errors: Array<AgentSettingsProviderError>, };

export type SettingOperation = { "type": "set", "data": { key: SettingKey, scope: SettingScope, value: JsonValue, } } | { "type": "unset", "data": { key: SettingKey, scope: SettingScope, } };

export type SettingsPatch = { provider: AgentSettingsProvider, project_path?: string | null, expected_file_revisions: { [key in string]?: string }, operations: Array<SettingOperation>, };

export type NativeFileDiff = { file_id: string, path: string, before: string, after: string, changed: boolean, };

export type SettingsDiff = { provider: AgentSettingsProvider, files: Array<NativeFileDiff>, warnings: Array<string>, };

export type ApplySettingsRequest = { patch: SettingsPatch, confirmed: boolean, };

export type NativeFilePatch = { provider: AgentSettingsProvider, project_path?: string | null, file_id: string, expected_revision: string, content: string, };

export type ApplyNativeFileRequest = { patch: NativeFilePatch, confirmed: boolean, };

export type ConfigProfile = { id: string, provider: AgentSettingsProvider, executor_profile: ExecutorProfileId, name: string, schema_version: number, setting_overrides: { [key in string]?: JsonValue }, provider_extensions: { [key in string]?: JsonValue }, environment: { [key in string]?: string }, custom_args: Array<string>, updated_at: string, };

export type SaveConfigProfileRequest = { profile: ConfigProfile, };

export type DeleteConfigProfileRequest = { id: string, };

export type DuplicateConfigProfileRequest = { id: string, name: string, };

export type CopyProfilePreviewRequest = { id: string, target_provider: AgentSettingsProvider, target_executor_profile: ExecutorProfileId, target_name: string, };

export type ProfileCopyPreview = { profile: ConfigProfile, compatible_keys: Array<string>, skipped_keys: Array<string>, warnings: Array<string>, };

export type ProfileApplyPreviewRequest = { id: string, project_path?: string | null, scope: SettingScope, expected_file_revisions: { [key in string]?: string }, };

export type ApplyConfigProfileRequest = { preview: ProfileApplyPreviewRequest, confirmed: boolean, };

export enum AgentSettingErrorCode { invalid_request = "invalid_request", invalid_configuration = "invalid_configuration", not_found = "not_found", stale_revision = "stale_revision", unsupported = "unsupported", unsafe_path = "unsafe_path", validation_failed = "validation_failed", io = "io", rollback_failed = "rollback_failed", verification_failed = "verification_failed" }

export type AgentSettingOperationError = { code: AgentSettingErrorCode, message: string, provider?: AgentSettingsProvider | null, file_id?: string | null, setting_key?: string | null, recovery: string, };

export type AgentSettingsDiscoveryQuery = { provider: AgentSettingsProvider | null, project_path: string | null, };

export type AgentSettingsProfilesQuery = { provider: AgentSettingsProvider | null, };

export type AgentToolProvider = "codex" | "claude_code" | "gemini" | "oh_my_pi";

export type AgentToolKind = "mcp_server" | "skill";

export type AgentToolScope = "user" | "project";

export type AgentToolState = "not_installed" | "enabled" | "disabled" | "error" | "unsupported";

export type AgentToolCapabilities = { editable: boolean, removable: boolean, toggleable: boolean, exportable: boolean, installable: boolean, };

export type McpTransport = "stdio" | "http";

export type McpServerDefinition = { transport: McpTransport, command?: string | null, args: Array<string>, cwd?: string | null, env: { [key in string]?: string }, url?: string | null, headers: { [key in string]?: string }, source_metadata: JsonValue, };

export type SkillFile = { path: string, content_base64: string, };

export type SkillDefinition = { description: string | null, files: Array<SkillFile>, };

export type AgentToolDefinition = { "type": "mcp_server", "data": McpServerDefinition } | { "type": "skill", "data": SkillDefinition };

export type AgentTool = { provider: AgentToolProvider, scope: AgentToolScope, kind: AgentToolKind, name: string, native_path: string, state: AgentToolState, capabilities: AgentToolCapabilities, revision: string, definition: AgentToolDefinition, error?: string | null, };

export type AgentToolProviderError = { provider: AgentToolProvider, message: string, };

export type AgentToolProviderInventory = { provider: AgentToolProvider, installed: boolean, items: Array<AgentTool>, limitations: Array<string>, errors: Array<string>, };

export type AgentToolInventory = { providers: Array<AgentToolProviderInventory>, errors: Array<AgentToolProviderError>, };

export type AgentToolLocator = { provider: AgentToolProvider, scope: AgentToolScope, kind: AgentToolKind, name: string, native_path?: string | null, project_path?: string | null, };

export type CreateAgentToolRequest = { target: AgentToolLocator, definition: AgentToolDefinition, replace: boolean, expected_revision?: string | null, };

export type UpdateAgentToolRequest = { target: AgentToolLocator, expected_revision: string, definition: AgentToolDefinition, };

export type RemoveAgentToolRequest = { target: AgentToolLocator, expected_revision: string, };

export type ToggleAgentToolRequest = { target: AgentToolLocator, expected_revision: string, enabled: boolean, };

export type CopyAgentToolRequest = { source: AgentToolLocator, expected_revision: string, target_provider: AgentToolProvider, target_scope: AgentToolScope, target_project_path?: string | null, target_name?: string | null, replace: boolean, target_expected_revision?: string | null, };

export type CopyAgentToolResponse = { item: AgentTool, source_metadata: JsonValue, warnings: Array<string>, };

export type AgentToolErrorCode = "invalid_request" | "invalid_configuration" | "not_found" | "collision" | "stale_revision" | "unsupported" | "unsafe_path" | "io" | "verification_failed";

export type AgentToolOperationError = { code: AgentToolErrorCode, message: string, provider?: AgentToolProvider | null, name?: string | null, };

export type AgentToolDiscoveryQuery = { project_path: string | null, };

export type AgentToolRevealResponse = { native_path: string, };

export type ExecutorActionType = { "type": "ScriptRequest" } & ScriptRequest;

export type ExecutorConfig = { 
/**
 * The executor type (e.g., CLAUDE_CODE, GEMINI)
 */
executor: BaseCodingAgent, 
/**
 * Optional variant/preset name (e.g., "PLAN", "ROUTER")
 */
variant?: string | null, 
/**
 * Model override (e.g., "anthropic/claude-sonnet-4-20250514")
 */
model_id?: string | null, 
/**
 * Agent mode override
 */
agent_id?: string | null, 
/**
 * Reasoning effort override (e.g., "high", "medium")
 */
reasoning_id?: string | null, 
/**
 * Permission policy override
 */
permission_policy?: PermissionPolicy | null, };

export type ScriptContext = "SetupScript" | "CleanupScript" | "ArchiveScript" | "DevServer" | "ToolInstallScript";

export type ScriptRequest = { script: string, language: ScriptRequestLanguage, context: ScriptContext, 
/**
 * Optional relative path to execute the script in (relative to container_ref).
 * If None, uses the container_ref directory directly.
 */
working_dir: string | null, };

export type ScriptRequestLanguage = "Bash";

export enum BaseCodingAgent { CLAUDE_CODE = "CLAUDE_CODE", GEMINI = "GEMINI", CODEX = "CODEX", OH_MY_PI = "OH_MY_PI" }

export type CodingAgent = { "CLAUDE_CODE": ClaudeCode } | { "GEMINI": Gemini } | { "CODEX": Codex } | { "OH_MY_PI": OhMyPi };

export type SlashCommandSource = "builtin" | "skill" | "plugin" | "custom" | "fallback";

export type SlashCommandSupportLevel = "product" | "native" | "skill" | "custom" | "diagnostic" | "unsupported" | "fallback";

export type SlashCommandDescription = { 
/**
 * Command name without the leading slash, e.g. `help` for `/help`.
 */
name: string, description?: string | null, source?: SlashCommandSource | null, support_level?: SlashCommandSupportLevel | null, };

export type AvailabilityInfo = { "type": "LOGIN_DETECTED", last_auth_timestamp: bigint, } | { "type": "INSTALLATION_FOUND" } | { "type": "NOT_FOUND" };

export type CommandBuilder = { 
/**
 * Base executable command (e.g., "claude", "codex", or "omp")
 */
base: string, 
/**
 * Optional parameters to append to the base command
 */
params: Array<string> | null, };

export type ExecutorProfileId = { 
/**
 * The executor type (e.g., "CLAUDE_CODE", "GEMINI")
 */
executor: BaseCodingAgent, 
/**
 * Optional variant name (e.g., "PLAN", "ROUTER")
 */
variant: string | null, };

export type ExecutorRecentModels = { 
/**
 * Ordered list of recently used model keys (most recent last).
 */
models?: Array<string>, 
/**
 * Last-used reasoning effort per model
 */
reasoning_by_model?: { [key in string]?: string }, };

export type ExecutorProfile = { recently_used_models?: ExecutorRecentModels | null, } & ({ [key in string]?: { "CLAUDE_CODE": ClaudeCode } | { "GEMINI": Gemini } | { "CODEX": Codex } | { "OH_MY_PI": OhMyPi } });

export type ExecutorConfigs = { executors: { [key in BaseCodingAgent]?: ExecutorProfile }, };

export enum BaseAgentCapability { SESSION_FORK = "SESSION_FORK", SETUP_HELPER = "SETUP_HELPER", CONTEXT_USAGE = "CONTEXT_USAGE" }

export enum AgentProviderCapability { INITIAL_RUN = "INITIAL_RUN", FOLLOW_UP = "FOLLOW_UP", SESSION_RESUME = "SESSION_RESUME", SESSION_FORK = "SESSION_FORK", GRACEFUL_CANCEL = "GRACEFUL_CANCEL", TOOL_PERMISSIONS = "TOOL_PERMISSIONS", MCP = "MCP", SETUP_HELPER = "SETUP_HELPER", CONTEXT_USAGE = "CONTEXT_USAGE", MODEL_SELECTOR = "MODEL_SELECTOR", OBSERVED_CONFIG = "OBSERVED_CONFIG", WORKFLOW_AGENT_STEP = "WORKFLOW_AGENT_STEP", TEAM_SLOT = "TEAM_SLOT" }

export type AgentProviderDiagnostic = { kind: AgentProviderDiagnosticKind, message: string, };

export enum AgentProviderDiagnosticKind { MISSING_EXECUTABLE = "MISSING_EXECUTABLE", AUTH_REQUIRED = "AUTH_REQUIRED", CONFIG_MISSING = "CONFIG_MISSING", UNSUPPORTED_PLATFORM = "UNSUPPORTED_PLATFORM", DISABLED_BY_POLICY = "DISABLED_BY_POLICY", LEGACY_LIMITED = "LEGACY_LIMITED", UNKNOWN = "UNKNOWN" }

export type AgentProviderPolicy = { executor: BaseCodingAgent, readiness: AgentProviderReadiness, capabilities: Array<AgentProviderCapability>, legacy: boolean, disabled: boolean, diagnostics: Array<AgentProviderDiagnostic>, };

export enum AgentProviderReadiness { UNKNOWN = "UNKNOWN", READY = "READY", INSTALLED = "INSTALLED", MISSING_EXECUTABLE = "MISSING_EXECUTABLE", AUTH_REQUIRED = "AUTH_REQUIRED", MISCONFIGURED = "MISCONFIGURED", UNSUPPORTED = "UNSUPPORTED", DISABLED = "DISABLED", DEGRADED = "DEGRADED" }

export type ClaudeEffort = "low" | "medium" | "high" | "xhigh" | "max";

export type ClaudeCode = { append_prompt: AppendPrompt, claude_code_router?: boolean | null, plan?: boolean | null, approvals?: boolean | null, model?: string | null, effort?: ClaudeEffort | null, agent?: string | null, dangerously_skip_permissions?: boolean | null, disable_api_key?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Gemini = { append_prompt: AppendPrompt, model?: string | null, yolo?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type OhMyPi = { append_prompt: AppendPrompt, model?: string | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Codex = { append_prompt: AppendPrompt, sandbox?: SandboxMode | null, ask_for_approval?: AskForApproval | null, oss?: boolean | null, model?: string | null, model_reasoning_effort?: ReasoningEffort | null, model_reasoning_summary?: ReasoningSummary | null, model_reasoning_summary_format?: ReasoningSummaryFormat | null, profile?: string | null, base_instructions?: string | null, include_apply_patch_tool?: boolean | null, model_provider?: string | null, compact_prompt?: string | null, developer_instructions?: string | null, plan: boolean, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type SandboxMode = "auto" | "read-only" | "workspace-write" | "danger-full-access";

export type AskForApproval = "unless-trusted" | "on-request" | "never";

export type ReasoningEffort = string;

export type ReasoningSummary = "auto" | "concise" | "detailed" | "none";

export type ReasoningSummaryFormat = "none" | "experimental";

export type AppendPrompt = string | null;

export type RepoReviewContext = { repo_id: string, repo_name: string, base_commit: string, };

export type CommandExitStatus = { "type": "exit_code", code: number, } | { "type": "success", success: boolean, };

export type CommandRunResult = { exit_status: CommandExitStatus | null, output: string | null, };

export type CommandCategory = "read" | "search" | "edit" | "fetch" | "other";

export type NormalizedEntry = { timestamp: string | null, entry_type: NormalizedEntryType, content: string, };

export type NormalizedEntryType = { "type": "user_message" } | { "type": "user_feedback", denied_tool: string, } | { "type": "assistant_message" } | { "type": "tool_use", tool_name: string, action_type: ActionType, status: ToolStatus, } | { "type": "system_message" } | { "type": "error_message", error_type: NormalizedEntryError, } | { "type": "thinking" } | { "type": "loading" } | { "type": "next_action", failed: boolean, execution_processes: number, needs_setup: boolean, } | { "type": "token_usage_info" } & TokenUsageInfo | { "type": "user_answered_questions", answers: Array<AnsweredQuestion>, };

export type TokenUsageInfo = { total_tokens: number, model_context_window: number, };

export type FileChange = { "action": "write", content: string, } | { "action": "delete" } | { "action": "rename", new_path: string, } | { "action": "edit", 
/**
 * Unified diff containing file header and hunks.
 */
unified_diff: string, 
/**
 * Whether line number in the hunks are reliable.
 */
has_line_numbers: boolean, };

export type ActionType = { "action": "file_read", path: string, } | { "action": "file_edit", path: string, changes: Array<FileChange>, } | { "action": "command_run", command: string, result: CommandRunResult | null, category: CommandCategory, } | { "action": "search", query: string, } | { "action": "web_fetch", url: string, } | { "action": "tool", tool_name: string, arguments: JsonValue | null, result: ToolResult | null, } | { "action": "task_create", description: string, subagent_type: string | null, result: ToolResult | null, } | { "action": "plan_presentation", plan: string, } | { "action": "todo_management", todos: Array<TodoItem>, operation: string, } | { "action": "ask_user_question", questions: Array<AskUserQuestionItem>, } | { "action": "other", description: string, };

export type AnsweredQuestion = { question: string, answer: Array<string>, };

export type AskUserQuestionItem = { question: string, header: string, options: Array<AskUserQuestionOption>, multiSelect: boolean, };

export type AskUserQuestionOption = { label: string, description: string, };

export type TodoItem = { content: string, status: string, priority: string | null, };

export type NormalizedEntryError = { "type": "setup_required" } | { "type": "other" };

export type ToolResult = { type: ToolResultValueType, 
/**
 * For Markdown, this will be a JSON string; for JSON, a structured value
 */
value: JsonValue, };

export type ToolResultValueType = { "type": "markdown" } | { "type": "json" };

export type ToolStatus = { "status": "created" } | { "status": "success" } | { "status": "failed" } | { "status": "denied", reason: string | null, } | { "status": "pending_approval", approval_id: string, } | { "status": "timed_out" };

export type PatchType = { "type": "NORMALIZED_ENTRY", "content": NormalizedEntry } | { "type": "STDOUT", "content": string } | { "type": "STDERR", "content": string } | { "type": "DIFF", "content": Diff };

export type ModelInfo = { 
/**
 * Model identifier
 */
id: string, 
/**
 * Display name
 */
name: string, 
/**
 * Provider this model belongs to
 */
provider_id?: string | null, 
/**
 * Configurable reasoning options if supported
 */
reasoning_options: Array<ReasoningOption>, };

export type ReasoningOption = { id: string, label: string, is_default: boolean, };

export type ModelProvider = { 
/**
 * Provider identifier
 */
id: string, 
/**
 * Display name
 */
name: string, };

export type AgentInfo = { id: string, label: string, description?: string | null, is_default: boolean, };

export enum PermissionPolicy { AUTO = "AUTO", SUPERVISED = "SUPERVISED", PLAN = "PLAN" }

export type ModelSelectorConfig = { 
/**
 * Available providers
 */
providers: Array<ModelProvider>, 
/**
 * Available models
 */
models: Array<ModelInfo>, 
/**
 * Global default model (format: provider_id/model_id)
 */
default_model?: string | null, 
/**
 * Available agents
 */
agents: Array<AgentInfo>, 
/**
 * Supported permission policies
 */
permissions: Array<PermissionPolicy>, };

export type CodexSkillDescription = { name: string, description: string, short_description: string | null, path: string, scope: string, enabled: boolean, };

export type CodexSkillLoadError = { path: string, message: string, };

export type ExecutorDiscoveredOptions = { model_selector: ModelSelectorConfig, slash_commands: Array<SlashCommandDescription>, skills: Array<CodexSkillDescription>, skill_errors: Array<CodexSkillLoadError>, loading_models: boolean, loading_agents: boolean, loading_slash_commands: boolean, loading_skills: boolean, error: string | null, };

export enum AgentRunLifecycle { starting = "starting", running = "running", waiting_approval = "waiting_approval", waiting_input = "waiting_input", cancelling = "cancelling", completed = "completed", failed = "failed", crashed = "crashed" }

export type AgentRuntimeError = { kind: AgentRuntimeErrorKind, message: string, provider?: string | null, launch_phase?: AgentRuntimeLaunchPhase | null, exit_code?: number | null, };

export enum AgentRuntimeErrorKind { executable_not_found = "executable_not_found", command_build_failed = "command_build_failed", auth_required = "auth_required", startup_failed = "startup_failed", protocol_failed = "protocol_failed", process_crashed = "process_crashed", output_parse_failed = "output_parse_failed", approval_cancelled = "approval_cancelled", approval_timed_out = "approval_timed_out", cancelled = "cancelled", unknown = "unknown" }

export enum AgentRuntimeLaunchPhase { command_build = "command_build", process_spawn = "process_spawn", protocol_connect = "protocol_connect", warmup = "warmup", session_resume = "session_resume", accepted = "accepted" }

export enum AgentRuntimeMessageRole { user = "user", assistant = "assistant", system = "system" }

export enum AgentRuntimeToolStatus { created = "created", running = "running", waiting_approval = "waiting_approval", approved = "approved", denied = "denied", succeeded = "succeeded", failed = "failed", timed_out = "timed_out" }

export enum AgentRunIntent { initial = "initial", follow_up = "follow_up", review = "review" }

export enum RunAttemptMode { launch = "launch", resume = "resume", restart = "restart" }

export enum WorkspaceMode { shared_workspace = "shared_workspace", isolated_worktree = "isolated_worktree" }

export type WorkspaceReference = { workspace_id: string, mode: WorkspaceMode, path: string, };

export enum AgentCapability { session_resume = "session_resume", steering = "steering", approval = "approval", images = "images", review = "review", mcp = "mcp", subagents = "subagents", token_usage = "token_usage" }

export enum CapabilityState { native = "native", emulated = "emulated", unsupported = "unsupported", unknown = "unknown" }

export enum CapabilitySource { runtime_profile = "runtime_profile", version_probe = "version_probe", runtime_probe = "runtime_probe", run_policy = "run_policy", unknown = "unknown" }

export type CapabilitySnapshotEntry = { capability: AgentCapability, state: CapabilityState, source: CapabilitySource, emulation_policy?: string | null, evidence?: JsonValue | null, };

export type CapabilitySnapshot = { schema_version: number, runtime_profile_id: string, provider_id: string, runtime_version?: string | null, protocol_version?: string | null, adapter_version: string, resolved_at: string, capabilities: Array<CapabilitySnapshotEntry>, };

export type ProviderSessionReference = { schema_version: number, provider_id: string, runtime_profile_id: string, provider_session_id: string, observed_at: string, metadata?: JsonValue | null, };

export type CanonicalMessage = { message_id: string, role: AgentRuntimeMessageRole, content: string, };

export type AgentRunRequestEnvelope = { schema_version: number, payload_version: number, request_id: string, idempotency_key: string, session_id: string, agent_run_id: string, turn_id: string, correlation_id: string, intent: AgentRunIntent, runtime_profile_id: string, provider_id: string, workspace: WorkspaceReference, input: CanonicalMessage, created_at: string, };

export enum AgentTransportKind { stdio_cli = "stdio_cli", stdio_rpc = "stdio_rpc", acp = "acp", app_server_jsonrpc = "app_server_jsonrpc", http_sidecar = "http_sidecar", in_process = "in_process" }

export type RunAttemptRequest = { schema_version: number, payload_version: number, request_id: string, idempotency_key: string, session_id: string, agent_run_id: string, turn_id: string, run_attempt_id: string, attempt_number: number, correlation_id: string, mode: RunAttemptMode, transport: AgentTransportKind, runtime_profile_id: string, provider_id: string, workspace: WorkspaceReference, capability_snapshot: CapabilitySnapshot, executor_config: ExecutorConfig, selected_skills?: Array<SelectedSkill> | null, reset_to_message_id?: string | null, provider_session?: ProviderSessionReference | null, created_at: string, };

export type NativeAuditReference = { stream_id: string, sequence: bigint, checksum?: string | null, };

export type AgentEventPayload = { "type": "lifecycle_changed", "data": { status: AgentRunStatus, } } | { "type": "session_observed", "data": { provider_session: ProviderSessionReference, } } | { "type": "message", "data": { message: CanonicalMessage, final_output: boolean, } } | { "type": "thinking", "data": { content: string, } } | { "type": "tool_call", "data": { tool_call_id?: string | null, tool_name: string, status: AgentRuntimeToolStatus, arguments?: JsonValue | null, result?: JsonValue | null, } } | { "type": "approval_requested", "data": { approval_id: string, tool_call_id?: string | null, tool_name: string, } } | { "type": "approval_resolved", "data": { approval_id: string, approved: boolean, reason?: string | null, } } | { "type": "input_requested", "data": { input_id: string, prompt: string, } } | { "type": "input_resolved", "data": { input_id: string, answered: boolean, } } | { "type": "token_usage", "data": { input_tokens: bigint, output_tokens: bigint, cached_input_tokens?: bigint | null, } } | { "type": "error", "data": { error: AgentRuntimeError, } } | { "type": "projection_degraded", "data": { reason: string, } } | { "type": "provider_extension", "data": { provider_namespace: string, provider_event: string, payload: JsonValue, } } | { "type": "unknown", "data": { event_type: string, payload: JsonValue, } };

export type AgentEventEnvelope = { schema_version: number, payload_version: number, event_id: string, session_id: string, agent_run_id: string, turn_id: string, run_attempt_id: string, run_attempt_number: number, sequence: bigint, correlation_id: string, orchestration_run_id?: string | null, orchestration_node_execution_id?: string | null, timestamp: string, native_refs?: Array<NativeAuditReference>, payload: AgentEventPayload, };

export enum AgentRunStatus { pending = "pending", starting = "starting", running = "running", awaiting_input = "awaiting_input", awaiting_approval = "awaiting_approval", cancelling = "cancelling", succeeded = "succeeded", failed = "failed", cancelled = "cancelled", crashed = "crashed", audit_failed = "audit_failed" }

export enum ProjectionStatus { current = "current", projection_degraded = "projection_degraded", rebuilding = "rebuilding" }

export type RunState = { state_schema_version: number, reducer_version: number, session_id: string, agent_run_id: string, turn_id: string, status: AgentRunStatus, projection_status: ProjectionStatus, last_run_attempt_id?: string | null, last_run_attempt_number: number, last_event_sequence: bigint, last_event_id?: string | null, provider_session?: ProviderSessionReference | null, terminal_output?: CanonicalMessage | null, last_error?: AgentRuntimeError | null, unknown_event_count: bigint, updated_at: string, };

export type AgentRunPortSnapshot = { agent_run_id: string, state: RunState, };

export type AgentEventCursor = { run_attempt_number: number, sequence: bigint, };

export type AgentRunSummary = { agent_run_id: string, session_id: string, turn_id: string, state: RunState, created_at: string, updated_at: string, };

export type AgentRunHistoryPage = { agent_run_id: string, state: RunState, events: Array<AgentEventEnvelope>, next_cursor: AgentEventCursor | null, has_more: boolean, };

export type AgentRunStats = { event_count: bigint, message_count: bigint, thinking_count: bigint, tool_call_count: bigint, approval_request_count: bigint, approval_resolution_count: bigint, input_request_count: bigint, input_resolution_count: bigint, error_count: bigint, provider_extension_count: bigint, unknown_event_count: bigint, input_tokens: bigint, output_tokens: bigint, cached_input_tokens: bigint, first_event_at: string | null, last_event_at: string | null, status: AgentRunStatus, projection_status: ProjectionStatus, };

export type AgentRunControlIdentity = { command_id: string, idempotency_key: string, correlation_id: string, created_at: string, };

export type CancelAgentRunRequest = { reason: string, command_id: string, idempotency_key: string, correlation_id: string, created_at: string, };

export type SubmitAgentRunInputRequest = { input_id: string, content: string, command_id: string, idempotency_key: string, correlation_id: string, created_at: string, };

export type ResolveAgentRunApprovalRequest = { approval_id: string, approved: boolean, reason?: string, command_id: string, idempotency_key: string, correlation_id: string, created_at: string, };

export type RetryAgentRunRequest = { mode: RunAttemptMode, run_attempt_id: string, command_id: string, idempotency_key: string, correlation_id: string, created_at: string, };

export enum OrchestrationProductKind { workflow = "workflow", arena = "arena" }

export enum OrchestrationFailurePolicy { fail_fast = "fail_fast", allow_partial = "allow_partial" }

export enum OrchestrationJoinPolicy { all = "all", any = "any", each = "each" }

export enum RemainingUpstreamsPolicy { continue = "continue", cancel_remaining = "cancel_remaining" }

export enum EachDownstreamExecution { parallel = "parallel", serial = "serial" }

export enum RetryBackoffKind { none = "none", fixed = "fixed", exponential = "exponential" }

export type OrchestrationRetryPolicy = { max_run_attempts: number, backoff: RetryBackoffKind, backoff_ms: bigint, retryable_terminal_statuses: Array<AgentRunStatus>, mode: RunAttemptMode, };

export type OrchestrationPlanNode = { node_key: string, stable_order: number, dependencies: Array<string>, join: OrchestrationJoinPolicy, failure_policy: OrchestrationFailurePolicy, remaining_upstreams: RemainingUpstreamsPolicy, each_downstream_execution: EachDownstreamExecution, retry: OrchestrationRetryPolicy, runtime_profile_id?: string | null, provider_id?: string | null, provider_config?: JsonValue | null, };

export type OrchestrationPlanSnapshot = { schema_version: number, plan_id: string, source_definition_id: string, source_definition_version: string, product_kind: OrchestrationProductKind, workspace_mode: WorkspaceMode, nodes: Array<OrchestrationPlanNode>, created_at: string, };

export type UpstreamSourceReference = { orchestration_run_id: string, node_execution_id: string, agent_run_id: string, };

export type UpstreamHandoff = { source_ref: UpstreamSourceReference, initiating_input: CanonicalMessage, terminal_output?: CanonicalMessage | null, };

export type AgentRunPortCommandEnvelope = { schema_version: number, command_id: string, idempotency_key: string, agent_run_id: string, orchestration_run_id?: string | null, orchestration_node_execution_id?: string | null, correlation_id: string, created_at: string, command: AgentRunPortCommand, };

export type AgentRunPortCommand = { "type": "create", "data": { request: AgentRunRequestEnvelope, attempt: RunAttemptRequest, } } | { "type": "cancel", "data": { reason: string, } } | { "type": "submit_input", "data": { input_id: string, content: string, } } | { "type": "resolve_approval", "data": { approval_id: string, approved: boolean, reason?: string | null, } } | { "type": "retry", "data": { mode: RunAttemptMode, run_attempt_id: string, } };

export enum OrchestrationRunStatus { pending = "pending", running = "running", waiting_for_input = "waiting_for_input", waiting_for_approval = "waiting_for_approval", cancelling = "cancelling", succeeded = "succeeded", failed = "failed", cancelled = "cancelled" }

export enum OrchestrationNodeStatus { pending = "pending", ready = "ready", running = "running", awaiting_input = "awaiting_input", awaiting_approval = "awaiting_approval", cancelling = "cancelling", succeeded = "succeeded", failed = "failed", cancelled = "cancelled" }

export type OrchestrationEventPayload = { "type": "lifecycle_changed", "data": { status: OrchestrationRunStatus, } } | { "type": "node_status_changed", "data": { node_execution_id: string, status: OrchestrationNodeStatus, } } | { "type": "agent_run_linked", "data": { node_execution_id: string, agent_run_id: string, } } | { "type": "join_decided", "data": { node_execution_id: string, policy: OrchestrationJoinPolicy, consumed_source_execution_ids: Array<string>, } } | { "type": "command_queued", "data": { command_id: string, idempotency_key: string, } } | { "type": "projection_degraded", "data": { reason: string, } } | { "type": "unknown", "data": { event_type: string, payload: JsonValue, } };

export type OrchestrationEventEnvelope = { schema_version: number, payload_version: number, event_id: string, orchestration_run_id: string, sequence: bigint, correlation_id: string, timestamp: string, payload: OrchestrationEventPayload, };

export type OrchestrationState = { state_schema_version: number, reducer_version: number, orchestration_run_id: string, status: OrchestrationRunStatus, projection_status: ProjectionStatus, last_event_sequence: bigint, last_event_id?: string | null, unknown_event_count: bigint, updated_at: string, };

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null;

export type RelayWsMessageType = "text" | "binary" | "ping" | "pong" | "close";

export type DataChannelMessage = { "type": "http_request" } & DataChannelRequest | { "type": "http_response" } & DataChannelResponse | { "type": "ws_open" } & WsOpen | { "type": "ws_opened" } & WsOpened | { "type": "ws_frame" } & WsFrame | { "type": "ws_close" } & WsClose | { "type": "ws_error" } & WsError;

export type DataChannelRequest = { id: string, method: string, path: string, headers: { [key in string]?: Array<string> }, 
/**
 * Base64-encoded request body, if any.
 */
body_b64?: string | null, };

export type DataChannelResponse = { id: string, status: number, headers: { [key in string]?: Array<string> }, 
/**
 * Base64-encoded response body, if any.
 */
body_b64?: string | null, };

export type WsOpen = { 
/**
 * Unique connection ID for multiplexing.
 */
conn_id: string, 
/**
 * Target path, e.g. `/api/sessions/abc/queue`.
 */
path: string, 
/**
 * Optional sub-protocol(s) to negotiate.
 */
protocols?: string | null, };

export type WsOpened = { conn_id: string, 
/**
 * The sub-protocol selected by the server, if any.
 */
selected_protocol?: string | null, };

export type WsFrame = { conn_id: string, msg_type: RelayWsMessageType, 
/**
 * Base64-encoded payload.
 */
payload_b64?: string | null, };

export type WsClose = { conn_id: string, 
/**
 * Close code (RFC 6455 §7.4).
 */
code?: number | null, 
/**
 * Close reason.
 */
reason?: string | null, };

export type WsError = { conn_id: string, error: string, };

export type SdpOffer = { 
/**
 * The SDP string from the peer's `RTCPeerConnection.createOffer()`.
 */
sdp: string, 
/**
 * Caller-provided session identifier to correlate offer/answer/candidates.
 */
session_id: string, };

export type SdpAnswer = { 
/**
 * The SDP string from `Rtc::direct_api().create_answer()`.
 */
sdp: string, 
/**
 * Echoed session identifier from the offer.
 */
session_id: string, };

export const DEFAULT_PR_DESCRIPTION_PROMPT = "Update the PR that was just created with a better title and description.\nThe PR number is #{pr_number} and the URL is {pr_url}.\n\nAnalyze the changes in this branch and write:\n1. A concise, descriptive title that summarizes the changes, postfixed with \"(Vibe Kanban)\"\n2. A detailed description that explains:\n   - What changes were made\n   - Why they were made (based on the task context)\n   - Any important implementation details\n   - At the end, include a note: \"This PR was written using [Vibe Kanban](https://vibekanban.com)\"\n\nUse the appropriate CLI tool to update the PR (gh pr edit for GitHub, az repos pr update for Azure DevOps).";

export const DEFAULT_COMMIT_REMINDER_PROMPT = "There are uncommitted changes. Please stage and commit them now with a descriptive commit message.";