/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingSignInRouteImport } from './routes/onboarding_.sign-in'
import { Route as AppWorkspacesRouteImport } from './routes/_app.workspaces'
import { Route as AppWorkflowsRouteImport } from './routes/_app.workflows'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppExportRouteImport } from './routes/_app.export'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAgentsRouteImport } from './routes/_app.agents'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as WorkspacesWorkspaceIdVscodeRouteImport } from './routes/workspaces.$workspaceId.vscode'
import { Route as AppWorkspacesElectricTestRouteImport } from './routes/_app.workspaces_.electric-test'
import { Route as AppWorkspacesCreateRouteImport } from './routes/_app.workspaces_.create'
import { Route as AppWorkspacesWorkspaceIdRouteImport } from './routes/_app.workspaces_.$workspaceId'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppProjectsProjectIdWorkflowsRouteImport } from './routes/_app.projects.$projectId_.workflows'
import { Route as AppHostsHostIdWorkspacesRouteImport } from './routes/_app.hosts.$hostId.workspaces'
import { Route as HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport } from './routes/hosts.$hostId.workspaces.$workspaceId.vscode'
import { Route as AppProjectsProjectIdWorkflowRunsRunIdRouteImport } from './routes/_app.projects.$projectId_.workflow-runs.$runId'
import { Route as AppProjectsProjectIdTasksTaskIdRouteImport } from './routes/_app.projects.$projectId_.tasks.$taskId'
import { Route as AppHostsHostIdWorkspacesCreateRouteImport } from './routes/_app.hosts.$hostId.workspaces_.create'
import { Route as AppHostsHostIdWorkspacesWorkspaceIdRouteImport } from './routes/_app.hosts.$hostId.workspaces_.$workspaceId'
import { Route as AppProjectsProjectIdWorkspacesCreateDraftIdRouteImport } from './routes/_app.projects.$projectId_.workspaces.create.$draftId'
import { Route as AppProjectsProjectIdWorkflowsWorkflowIdEditRouteImport } from './routes/_app.projects.$projectId_.workflows_.$workflowId.edit'
import { Route as AppProjectsProjectIdTasksTaskIdWorkspacesWorkspaceIdRouteImport } from './routes/_app.projects.$projectId_.tasks.$taskId_.workspaces.$workspaceId'
import { Route as AppProjectsProjectIdTasksTaskIdArenaGroupIdRouteImport } from './routes/_app.projects.$projectId_.tasks.$taskId_.arena.$groupId'
import { Route as AppProjectsProjectIdTasksTaskIdWorkspacesCreateDraftIdRouteImport } from './routes/_app.projects.$projectId_.tasks.$taskId_.workspaces.create.$draftId'
import { Route as AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRouteImport } from './routes/_app.projects.$projectId_.hosts.$hostId.workspaces.create.$draftId'
import { Route as AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesWorkspaceIdRouteImport } from './routes/_app.projects.$projectId_.tasks.$taskId_.hosts.$hostId.workspaces.$workspaceId'
import { Route as AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesCreateDraftIdRouteImport } from './routes/_app.projects.$projectId_.tasks.$taskId_.hosts.$hostId.workspaces.create.$draftId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSignInRoute = OnboardingSignInRouteImport.update({
  id: '/onboarding_/sign-in',
  path: '/onboarding/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspacesRoute = AppWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const WorkspacesWorkspaceIdVscodeRoute =
  WorkspacesWorkspaceIdVscodeRouteImport.update({
    id: '/workspaces/$workspaceId/vscode',
    path: '/workspaces/$workspaceId/vscode',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesElectricTestRoute =
  AppWorkspacesElectricTestRouteImport.update({
    id: '/workspaces_/electric-test',
    path: '/workspaces/electric-test',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorkspacesCreateRoute = AppWorkspacesCreateRouteImport.update({
  id: '/workspaces_/create',
  path: '/workspaces/create',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesWorkspaceIdRoute =
  AppWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces_/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectIdWorkflowsRoute =
  AppProjectsProjectIdWorkflowsRouteImport.update({
    id: '/$projectId_/workflows',
    path: '/$projectId/workflows',
    getParentRoute: () => AppProjectsRoute,
  } as any)
const AppHostsHostIdWorkspacesRoute =
  AppHostsHostIdWorkspacesRouteImport.update({
    id: '/hosts/$hostId/workspaces',
    path: '/hosts/$hostId/workspaces',
    getParentRoute: () => AppRoute,
  } as any)
const HostsHostIdWorkspacesWorkspaceIdVscodeRoute =
  HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport.update({
    id: '/hosts/$hostId/workspaces/$workspaceId/vscode',
    path: '/hosts/$hostId/workspaces/$workspaceId/vscode',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppProjectsProjectIdWorkflowRunsRunIdRoute =
  AppProjectsProjectIdWorkflowRunsRunIdRouteImport.update({
    id: '/$projectId_/workflow-runs/$runId',
    path: '/$projectId/workflow-runs/$runId',
    getParentRoute: () => AppProjectsRoute,
  } as any)
const AppProjectsProjectIdTasksTaskIdRoute =
  AppProjectsProjectIdTasksTaskIdRouteImport.update({
    id: '/$projectId_/tasks/$taskId',
    path: '/$projectId/tasks/$taskId',
    getParentRoute: () => AppProjectsRoute,
  } as any)
const AppHostsHostIdWorkspacesCreateRoute =
  AppHostsHostIdWorkspacesCreateRouteImport.update({
    id: '/hosts/$hostId/workspaces_/create',
    path: '/hosts/$hostId/workspaces/create',
    getParentRoute: () => AppRoute,
  } as any)
const AppHostsHostIdWorkspacesWorkspaceIdRoute =
  AppHostsHostIdWorkspacesWorkspaceIdRouteImport.update({
    id: '/hosts/$hostId/workspaces_/$workspaceId',
    path: '/hosts/$hostId/workspaces/$workspaceId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdWorkspacesCreateDraftIdRoute =
  AppProjectsProjectIdWorkspacesCreateDraftIdRouteImport.update({
    id: '/$projectId_/workspaces/create/$draftId',
    path: '/$projectId/workspaces/create/$draftId',
    getParentRoute: () => AppProjectsRoute,
  } as any)
const AppProjectsProjectIdWorkflowsWorkflowIdEditRoute =
  AppProjectsProjectIdWorkflowsWorkflowIdEditRouteImport.update({
    id: '/$projectId_/workflows_/$workflowId/edit',
    path: '/$projectId/workflows/$workflowId/edit',
    getParentRoute: () => AppProjectsRoute,
  } as any)
const AppProjectsProjectIdTasksTaskIdWorkspacesWorkspaceIdRoute =
  AppProjectsProjectIdTasksTaskIdWorkspacesWorkspaceIdRouteImport.update({
    id: '/$projectId_/tasks/$taskId_/workspaces/$workspaceId',
    path: '/$projectId/tasks/$taskId/workspaces/$workspaceId',
    getParentRoute: () => AppProjectsRoute,
  } as any)
const AppProjectsProjectIdTasksTaskIdArenaGroupIdRoute =
  AppProjectsProjectIdTasksTaskIdArenaGroupIdRouteImport.update({
    id: '/$projectId_/tasks/$taskId_/arena/$groupId',
    path: '/$projectId/tasks/$taskId/arena/$groupId',
    getParentRoute: () => AppProjectsRoute,
  } as any)
const AppProjectsProjectIdTasksTaskIdWorkspacesCreateDraftIdRoute =
  AppProjectsProjectIdTasksTaskIdWorkspacesCreateDraftIdRouteImport.update({
    id: '/$projectId_/tasks/$taskId_/workspaces/create/$draftId',
    path: '/$projectId/tasks/$taskId/workspaces/create/$draftId',
    getParentRoute: () => AppProjectsRoute,
  } as any)
const AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute =
  AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRouteImport.update({
    id: '/$projectId_/hosts/$hostId/workspaces/create/$draftId',
    path: '/$projectId/hosts/$hostId/workspaces/create/$draftId',
    getParentRoute: () => AppProjectsRoute,
  } as any)
const AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesWorkspaceIdRoute =
  AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesWorkspaceIdRouteImport.update(
    {
      id: '/$projectId_/tasks/$taskId_/hosts/$hostId/workspaces/$workspaceId',
      path: '/$projectId/tasks/$taskId/hosts/$hostId/workspaces/$workspaceId',
      getParentRoute: () => AppProjectsRoute,
    } as any,
  )
const AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesCreateDraftIdRoute =
  AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesCreateDraftIdRouteImport.update(
    {
      id: '/$projectId_/tasks/$taskId_/hosts/$hostId/workspaces/create/$draftId',
      path: '/$projectId/tasks/$taskId/hosts/$hostId/workspaces/create/$draftId',
      getParentRoute: () => AppProjectsRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/agents': typeof AppAgentsRoute
  '/dashboard': typeof AppDashboardRoute
  '/export': typeof AppExportRoute
  '/notifications': typeof AppNotificationsRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/workflows': typeof AppWorkflowsRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/onboarding/sign-in': typeof OnboardingSignInRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/workspaces/create': typeof AppWorkspacesCreateRoute
  '/workspaces/electric-test': typeof AppWorkspacesElectricTestRoute
  '/workspaces/$workspaceId/vscode': typeof WorkspacesWorkspaceIdVscodeRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/hosts/$hostId/workspaces': typeof AppHostsHostIdWorkspacesRoute
  '/projects/$projectId/workflows': typeof AppProjectsProjectIdWorkflowsRoute
  '/hosts/$hostId/workspaces/$workspaceId': typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces/create': typeof AppHostsHostIdWorkspacesCreateRoute
  '/projects/$projectId/tasks/$taskId': typeof AppProjectsProjectIdTasksTaskIdRoute
  '/projects/$projectId/workflow-runs/$runId': typeof AppProjectsProjectIdWorkflowRunsRunIdRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
  '/projects/$projectId/workflows/$workflowId/edit': typeof AppProjectsProjectIdWorkflowsWorkflowIdEditRoute
  '/projects/$projectId/workspaces/create/$draftId': typeof AppProjectsProjectIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/tasks/$taskId/arena/$groupId': typeof AppProjectsProjectIdTasksTaskIdArenaGroupIdRoute
  '/projects/$projectId/tasks/$taskId/workspaces/$workspaceId': typeof AppProjectsProjectIdTasksTaskIdWorkspacesWorkspaceIdRoute
  '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId': typeof AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/tasks/$taskId/workspaces/create/$draftId': typeof AppProjectsProjectIdTasksTaskIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/tasks/$taskId/hosts/$hostId/workspaces/$workspaceId': typeof AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesWorkspaceIdRoute
  '/projects/$projectId/tasks/$taskId/hosts/$hostId/workspaces/create/$draftId': typeof AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesCreateDraftIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/agents': typeof AppAgentsRoute
  '/dashboard': typeof AppDashboardRoute
  '/export': typeof AppExportRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/workflows': typeof AppWorkflowsRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/onboarding/sign-in': typeof OnboardingSignInRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/workspaces/create': typeof AppWorkspacesCreateRoute
  '/workspaces/electric-test': typeof AppWorkspacesElectricTestRoute
  '/workspaces/$workspaceId/vscode': typeof WorkspacesWorkspaceIdVscodeRoute
  '/projects': typeof AppProjectsIndexRoute
  '/hosts/$hostId/workspaces': typeof AppHostsHostIdWorkspacesRoute
  '/projects/$projectId/workflows': typeof AppProjectsProjectIdWorkflowsRoute
  '/hosts/$hostId/workspaces/$workspaceId': typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces/create': typeof AppHostsHostIdWorkspacesCreateRoute
  '/projects/$projectId/tasks/$taskId': typeof AppProjectsProjectIdTasksTaskIdRoute
  '/projects/$projectId/workflow-runs/$runId': typeof AppProjectsProjectIdWorkflowRunsRunIdRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
  '/projects/$projectId/workflows/$workflowId/edit': typeof AppProjectsProjectIdWorkflowsWorkflowIdEditRoute
  '/projects/$projectId/workspaces/create/$draftId': typeof AppProjectsProjectIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/tasks/$taskId/arena/$groupId': typeof AppProjectsProjectIdTasksTaskIdArenaGroupIdRoute
  '/projects/$projectId/tasks/$taskId/workspaces/$workspaceId': typeof AppProjectsProjectIdTasksTaskIdWorkspacesWorkspaceIdRoute
  '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId': typeof AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/tasks/$taskId/workspaces/create/$draftId': typeof AppProjectsProjectIdTasksTaskIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/tasks/$taskId/hosts/$hostId/workspaces/$workspaceId': typeof AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesWorkspaceIdRoute
  '/projects/$projectId/tasks/$taskId/hosts/$hostId/workspaces/create/$draftId': typeof AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesCreateDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/agents': typeof AppAgentsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/export': typeof AppExportRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/workflows': typeof AppWorkflowsRoute
  '/_app/workspaces': typeof AppWorkspacesRoute
  '/onboarding_/sign-in': typeof OnboardingSignInRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/workspaces_/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/_app/workspaces_/create': typeof AppWorkspacesCreateRoute
  '/_app/workspaces_/electric-test': typeof AppWorkspacesElectricTestRoute
  '/workspaces/$workspaceId/vscode': typeof WorkspacesWorkspaceIdVscodeRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/hosts/$hostId/workspaces': typeof AppHostsHostIdWorkspacesRoute
  '/_app/projects/$projectId_/workflows': typeof AppProjectsProjectIdWorkflowsRoute
  '/_app/hosts/$hostId/workspaces_/$workspaceId': typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
  '/_app/hosts/$hostId/workspaces_/create': typeof AppHostsHostIdWorkspacesCreateRoute
  '/_app/projects/$projectId_/tasks/$taskId': typeof AppProjectsProjectIdTasksTaskIdRoute
  '/_app/projects/$projectId_/workflow-runs/$runId': typeof AppProjectsProjectIdWorkflowRunsRunIdRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
  '/_app/projects/$projectId_/workflows_/$workflowId/edit': typeof AppProjectsProjectIdWorkflowsWorkflowIdEditRoute
  '/_app/projects/$projectId_/workspaces/create/$draftId': typeof AppProjectsProjectIdWorkspacesCreateDraftIdRoute
  '/_app/projects/$projectId_/tasks/$taskId_/arena/$groupId': typeof AppProjectsProjectIdTasksTaskIdArenaGroupIdRoute
  '/_app/projects/$projectId_/tasks/$taskId_/workspaces/$workspaceId': typeof AppProjectsProjectIdTasksTaskIdWorkspacesWorkspaceIdRoute
  '/_app/projects/$projectId_/hosts/$hostId/workspaces/create/$draftId': typeof AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute
  '/_app/projects/$projectId_/tasks/$taskId_/workspaces/create/$draftId': typeof AppProjectsProjectIdTasksTaskIdWorkspacesCreateDraftIdRoute
  '/_app/projects/$projectId_/tasks/$taskId_/hosts/$hostId/workspaces/$workspaceId': typeof AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesWorkspaceIdRoute
  '/_app/projects/$projectId_/tasks/$taskId_/hosts/$hostId/workspaces/create/$draftId': typeof AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesCreateDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/agents'
    | '/dashboard'
    | '/export'
    | '/notifications'
    | '/projects'
    | '/settings'
    | '/workflows'
    | '/workspaces'
    | '/onboarding/sign-in'
    | '/projects/$projectId'
    | '/workspaces/$workspaceId'
    | '/workspaces/create'
    | '/workspaces/electric-test'
    | '/workspaces/$workspaceId/vscode'
    | '/projects/'
    | '/hosts/$hostId/workspaces'
    | '/projects/$projectId/workflows'
    | '/hosts/$hostId/workspaces/$workspaceId'
    | '/hosts/$hostId/workspaces/create'
    | '/projects/$projectId/tasks/$taskId'
    | '/projects/$projectId/workflow-runs/$runId'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
    | '/projects/$projectId/workflows/$workflowId/edit'
    | '/projects/$projectId/workspaces/create/$draftId'
    | '/projects/$projectId/tasks/$taskId/arena/$groupId'
    | '/projects/$projectId/tasks/$taskId/workspaces/$workspaceId'
    | '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId'
    | '/projects/$projectId/tasks/$taskId/workspaces/create/$draftId'
    | '/projects/$projectId/tasks/$taskId/hosts/$hostId/workspaces/$workspaceId'
    | '/projects/$projectId/tasks/$taskId/hosts/$hostId/workspaces/create/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/agents'
    | '/dashboard'
    | '/export'
    | '/notifications'
    | '/settings'
    | '/workflows'
    | '/workspaces'
    | '/onboarding/sign-in'
    | '/projects/$projectId'
    | '/workspaces/$workspaceId'
    | '/workspaces/create'
    | '/workspaces/electric-test'
    | '/workspaces/$workspaceId/vscode'
    | '/projects'
    | '/hosts/$hostId/workspaces'
    | '/projects/$projectId/workflows'
    | '/hosts/$hostId/workspaces/$workspaceId'
    | '/hosts/$hostId/workspaces/create'
    | '/projects/$projectId/tasks/$taskId'
    | '/projects/$projectId/workflow-runs/$runId'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
    | '/projects/$projectId/workflows/$workflowId/edit'
    | '/projects/$projectId/workspaces/create/$draftId'
    | '/projects/$projectId/tasks/$taskId/arena/$groupId'
    | '/projects/$projectId/tasks/$taskId/workspaces/$workspaceId'
    | '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId'
    | '/projects/$projectId/tasks/$taskId/workspaces/create/$draftId'
    | '/projects/$projectId/tasks/$taskId/hosts/$hostId/workspaces/$workspaceId'
    | '/projects/$projectId/tasks/$taskId/hosts/$hostId/workspaces/create/$draftId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/_app/agents'
    | '/_app/dashboard'
    | '/_app/export'
    | '/_app/notifications'
    | '/_app/projects'
    | '/_app/settings'
    | '/_app/workflows'
    | '/_app/workspaces'
    | '/onboarding_/sign-in'
    | '/_app/projects/$projectId'
    | '/_app/workspaces_/$workspaceId'
    | '/_app/workspaces_/create'
    | '/_app/workspaces_/electric-test'
    | '/workspaces/$workspaceId/vscode'
    | '/_app/projects/'
    | '/_app/hosts/$hostId/workspaces'
    | '/_app/projects/$projectId_/workflows'
    | '/_app/hosts/$hostId/workspaces_/$workspaceId'
    | '/_app/hosts/$hostId/workspaces_/create'
    | '/_app/projects/$projectId_/tasks/$taskId'
    | '/_app/projects/$projectId_/workflow-runs/$runId'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
    | '/_app/projects/$projectId_/workflows_/$workflowId/edit'
    | '/_app/projects/$projectId_/workspaces/create/$draftId'
    | '/_app/projects/$projectId_/tasks/$taskId_/arena/$groupId'
    | '/_app/projects/$projectId_/tasks/$taskId_/workspaces/$workspaceId'
    | '/_app/projects/$projectId_/hosts/$hostId/workspaces/create/$draftId'
    | '/_app/projects/$projectId_/tasks/$taskId_/workspaces/create/$draftId'
    | '/_app/projects/$projectId_/tasks/$taskId_/hosts/$hostId/workspaces/$workspaceId'
    | '/_app/projects/$projectId_/tasks/$taskId_/hosts/$hostId/workspaces/create/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  OnboardingSignInRoute: typeof OnboardingSignInRoute
  WorkspacesWorkspaceIdVscodeRoute: typeof WorkspacesWorkspaceIdVscodeRoute
  HostsHostIdWorkspacesWorkspaceIdVscodeRoute: typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding_/sign-in': {
      id: '/onboarding_/sign-in'
      path: '/onboarding/sign-in'
      fullPath: '/onboarding/sign-in'
      preLoaderRoute: typeof OnboardingSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspaces': {
      id: '/_app/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AppWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows': {
      id: '/_app/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/export': {
      id: '/_app/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/workspaces/$workspaceId/vscode': {
      id: '/workspaces/$workspaceId/vscode'
      path: '/workspaces/$workspaceId/vscode'
      fullPath: '/workspaces/$workspaceId/vscode'
      preLoaderRoute: typeof WorkspacesWorkspaceIdVscodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspaces_/electric-test': {
      id: '/_app/workspaces_/electric-test'
      path: '/workspaces/electric-test'
      fullPath: '/workspaces/electric-test'
      preLoaderRoute: typeof AppWorkspacesElectricTestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces_/create': {
      id: '/_app/workspaces_/create'
      path: '/workspaces/create'
      fullPath: '/workspaces/create'
      preLoaderRoute: typeof AppWorkspacesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces_/$workspaceId': {
      id: '/_app/workspaces_/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectId_/workflows': {
      id: '/_app/projects/$projectId_/workflows'
      path: '/$projectId/workflows'
      fullPath: '/projects/$projectId/workflows'
      preLoaderRoute: typeof AppProjectsProjectIdWorkflowsRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/hosts/$hostId/workspaces': {
      id: '/_app/hosts/$hostId/workspaces'
      path: '/hosts/$hostId/workspaces'
      fullPath: '/hosts/$hostId/workspaces'
      preLoaderRoute: typeof AppHostsHostIdWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/hosts/$hostId/workspaces/$workspaceId/vscode': {
      id: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      path: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      fullPath: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      preLoaderRoute: typeof HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/$projectId_/workflow-runs/$runId': {
      id: '/_app/projects/$projectId_/workflow-runs/$runId'
      path: '/$projectId/workflow-runs/$runId'
      fullPath: '/projects/$projectId/workflow-runs/$runId'
      preLoaderRoute: typeof AppProjectsProjectIdWorkflowRunsRunIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectId_/tasks/$taskId': {
      id: '/_app/projects/$projectId_/tasks/$taskId'
      path: '/$projectId/tasks/$taskId'
      fullPath: '/projects/$projectId/tasks/$taskId'
      preLoaderRoute: typeof AppProjectsProjectIdTasksTaskIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/hosts/$hostId/workspaces_/create': {
      id: '/_app/hosts/$hostId/workspaces_/create'
      path: '/hosts/$hostId/workspaces/create'
      fullPath: '/hosts/$hostId/workspaces/create'
      preLoaderRoute: typeof AppHostsHostIdWorkspacesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hosts/$hostId/workspaces_/$workspaceId': {
      id: '/_app/hosts/$hostId/workspaces_/$workspaceId'
      path: '/hosts/$hostId/workspaces/$workspaceId'
      fullPath: '/hosts/$hostId/workspaces/$workspaceId'
      preLoaderRoute: typeof AppHostsHostIdWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/workspaces/create/$draftId': {
      id: '/_app/projects/$projectId_/workspaces/create/$draftId'
      path: '/$projectId/workspaces/create/$draftId'
      fullPath: '/projects/$projectId/workspaces/create/$draftId'
      preLoaderRoute: typeof AppProjectsProjectIdWorkspacesCreateDraftIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectId_/workflows_/$workflowId/edit': {
      id: '/_app/projects/$projectId_/workflows_/$workflowId/edit'
      path: '/$projectId/workflows/$workflowId/edit'
      fullPath: '/projects/$projectId/workflows/$workflowId/edit'
      preLoaderRoute: typeof AppProjectsProjectIdWorkflowsWorkflowIdEditRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectId_/tasks/$taskId_/workspaces/$workspaceId': {
      id: '/_app/projects/$projectId_/tasks/$taskId_/workspaces/$workspaceId'
      path: '/$projectId/tasks/$taskId/workspaces/$workspaceId'
      fullPath: '/projects/$projectId/tasks/$taskId/workspaces/$workspaceId'
      preLoaderRoute: typeof AppProjectsProjectIdTasksTaskIdWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectId_/tasks/$taskId_/arena/$groupId': {
      id: '/_app/projects/$projectId_/tasks/$taskId_/arena/$groupId'
      path: '/$projectId/tasks/$taskId/arena/$groupId'
      fullPath: '/projects/$projectId/tasks/$taskId/arena/$groupId'
      preLoaderRoute: typeof AppProjectsProjectIdTasksTaskIdArenaGroupIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectId_/tasks/$taskId_/workspaces/create/$draftId': {
      id: '/_app/projects/$projectId_/tasks/$taskId_/workspaces/create/$draftId'
      path: '/$projectId/tasks/$taskId/workspaces/create/$draftId'
      fullPath: '/projects/$projectId/tasks/$taskId/workspaces/create/$draftId'
      preLoaderRoute: typeof AppProjectsProjectIdTasksTaskIdWorkspacesCreateDraftIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectId_/hosts/$hostId/workspaces/create/$draftId': {
      id: '/_app/projects/$projectId_/hosts/$hostId/workspaces/create/$draftId'
      path: '/$projectId/hosts/$hostId/workspaces/create/$draftId'
      fullPath: '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId'
      preLoaderRoute: typeof AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectId_/tasks/$taskId_/hosts/$hostId/workspaces/$workspaceId': {
      id: '/_app/projects/$projectId_/tasks/$taskId_/hosts/$hostId/workspaces/$workspaceId'
      path: '/$projectId/tasks/$taskId/hosts/$hostId/workspaces/$workspaceId'
      fullPath: '/projects/$projectId/tasks/$taskId/hosts/$hostId/workspaces/$workspaceId'
      preLoaderRoute: typeof AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectId_/tasks/$taskId_/hosts/$hostId/workspaces/create/$draftId': {
      id: '/_app/projects/$projectId_/tasks/$taskId_/hosts/$hostId/workspaces/create/$draftId'
      path: '/$projectId/tasks/$taskId/hosts/$hostId/workspaces/create/$draftId'
      fullPath: '/projects/$projectId/tasks/$taskId/hosts/$hostId/workspaces/create/$draftId'
      preLoaderRoute: typeof AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesCreateDraftIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
  }
}

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppProjectsProjectIdWorkflowsRoute: typeof AppProjectsProjectIdWorkflowsRoute
  AppProjectsProjectIdTasksTaskIdRoute: typeof AppProjectsProjectIdTasksTaskIdRoute
  AppProjectsProjectIdWorkflowRunsRunIdRoute: typeof AppProjectsProjectIdWorkflowRunsRunIdRoute
  AppProjectsProjectIdWorkflowsWorkflowIdEditRoute: typeof AppProjectsProjectIdWorkflowsWorkflowIdEditRoute
  AppProjectsProjectIdWorkspacesCreateDraftIdRoute: typeof AppProjectsProjectIdWorkspacesCreateDraftIdRoute
  AppProjectsProjectIdTasksTaskIdArenaGroupIdRoute: typeof AppProjectsProjectIdTasksTaskIdArenaGroupIdRoute
  AppProjectsProjectIdTasksTaskIdWorkspacesWorkspaceIdRoute: typeof AppProjectsProjectIdTasksTaskIdWorkspacesWorkspaceIdRoute
  AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute: typeof AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute
  AppProjectsProjectIdTasksTaskIdWorkspacesCreateDraftIdRoute: typeof AppProjectsProjectIdTasksTaskIdWorkspacesCreateDraftIdRoute
  AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesWorkspaceIdRoute: typeof AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesWorkspaceIdRoute
  AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesCreateDraftIdRoute: typeof AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesCreateDraftIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppProjectsProjectIdWorkflowsRoute: AppProjectsProjectIdWorkflowsRoute,
  AppProjectsProjectIdTasksTaskIdRoute: AppProjectsProjectIdTasksTaskIdRoute,
  AppProjectsProjectIdWorkflowRunsRunIdRoute:
    AppProjectsProjectIdWorkflowRunsRunIdRoute,
  AppProjectsProjectIdWorkflowsWorkflowIdEditRoute:
    AppProjectsProjectIdWorkflowsWorkflowIdEditRoute,
  AppProjectsProjectIdWorkspacesCreateDraftIdRoute:
    AppProjectsProjectIdWorkspacesCreateDraftIdRoute,
  AppProjectsProjectIdTasksTaskIdArenaGroupIdRoute:
    AppProjectsProjectIdTasksTaskIdArenaGroupIdRoute,
  AppProjectsProjectIdTasksTaskIdWorkspacesWorkspaceIdRoute:
    AppProjectsProjectIdTasksTaskIdWorkspacesWorkspaceIdRoute,
  AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute:
    AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute,
  AppProjectsProjectIdTasksTaskIdWorkspacesCreateDraftIdRoute:
    AppProjectsProjectIdTasksTaskIdWorkspacesCreateDraftIdRoute,
  AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesWorkspaceIdRoute:
    AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesWorkspaceIdRoute,
  AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesCreateDraftIdRoute:
    AppProjectsProjectIdTasksTaskIdHostsHostIdWorkspacesCreateDraftIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExportRoute: typeof AppExportRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
  AppWorkspacesRoute: typeof AppWorkspacesRoute
  AppWorkspacesWorkspaceIdRoute: typeof AppWorkspacesWorkspaceIdRoute
  AppWorkspacesCreateRoute: typeof AppWorkspacesCreateRoute
  AppWorkspacesElectricTestRoute: typeof AppWorkspacesElectricTestRoute
  AppHostsHostIdWorkspacesRoute: typeof AppHostsHostIdWorkspacesRoute
  AppHostsHostIdWorkspacesWorkspaceIdRoute: typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
  AppHostsHostIdWorkspacesCreateRoute: typeof AppHostsHostIdWorkspacesCreateRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExportRoute: AppExportRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
  AppWorkspacesRoute: AppWorkspacesRoute,
  AppWorkspacesWorkspaceIdRoute: AppWorkspacesWorkspaceIdRoute,
  AppWorkspacesCreateRoute: AppWorkspacesCreateRoute,
  AppWorkspacesElectricTestRoute: AppWorkspacesElectricTestRoute,
  AppHostsHostIdWorkspacesRoute: AppHostsHostIdWorkspacesRoute,
  AppHostsHostIdWorkspacesWorkspaceIdRoute:
    AppHostsHostIdWorkspacesWorkspaceIdRoute,
  AppHostsHostIdWorkspacesCreateRoute: AppHostsHostIdWorkspacesCreateRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  OnboardingSignInRoute: OnboardingSignInRoute,
  WorkspacesWorkspaceIdVscodeRoute: WorkspacesWorkspaceIdVscodeRoute,
  HostsHostIdWorkspacesWorkspaceIdVscodeRoute:
    HostsHostIdWorkspacesWorkspaceIdVscodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
