use std::{env, fs, path::Path};

use relay_types::{CreateRemoteSessionResponse, ListRelayHostsResponse, RelayHost};
use ts_rs::TS;

use crate::{
    Attachment, AttachmentUrlResponse, AttachmentWithBlob, Blob, CommitAttachmentsRequest,
    CommitAttachmentsResponse, ConfirmUploadRequest, CreateProjectRequest,
    CreateProjectStatusRequest, CreatePullRequestTaskRequest, CreateTagRequest,
    CreateTaskAssigneeRequest, CreateTaskCommentReactionRequest, CreateTaskCommentRequest,
    CreateTaskFollowerRequest, CreateTaskRelationshipRequest, CreateTaskRequest,
    CreateTaskTagRequest, ExportRequest, InitUploadRequest, InitUploadResponse, ListTasksQuery,
    ListTasksResponse, MemberRole, Notification, NotificationGroupKind, NotificationPayload,
    NotificationType, OrganizationMember, Project, ProjectStatus, PullRequest, PullRequestStatus,
    PullRequestTask, SearchTasksRequest, SortDirection, Tag, Task, TaskAssignee, TaskComment,
    TaskCommentReaction, TaskFollower, TaskPriority, TaskRelationship, TaskRelationshipType,
    TaskSortField, TaskTag, UpdateNotificationRequest, UpdateProjectRequest,
    UpdateProjectStatusRequest, UpdateTagRequest, UpdateTaskCommentReactionRequest,
    UpdateTaskCommentRequest, UpdateTaskRequest, User, UserData, Workspace,
    contracts::{mutations::all_mutation_definitions, shapes::all_shapes},
};

pub fn generate_remote_types() {
    let args: Vec<String> = env::args().collect();
    let check_mode = args.iter().any(|arg| arg == "--check");

    let typescript = export_shapes();

    // Path to shared/remote-types.ts relative to workspace root
    let output_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent() // crates/
        .unwrap()
        .parent() // workspace root
        .unwrap()
        .join("shared/remote-types.ts");

    if check_mode {
        let current = fs::read_to_string(&output_path).unwrap_or_default();
        if current == typescript {
            println!("✅ shared/remote-types.ts is up to date.");
            std::process::exit(0);
        } else {
            eprintln!("❌ shared/remote-types.ts is not up to date.");
            eprintln!("Please run 'pnpm run remote:generate-types' and commit the changes.");
            std::process::exit(1);
        }
    } else {
        fs::write(&output_path, &typescript).expect("Failed to write remote-types.ts");
        println!(
            "✅ Generated remote types and shapes to {}",
            output_path.display()
        );
    }
}

pub fn export_shapes() -> String {
    let shapes = all_shapes();

    let mut output = String::new();

    // Header
    output.push_str(
        "// This file was auto-generated by api-types' shared remote contract generator.\n",
    );
    output.push_str("// Do not edit manually.\n\n");

    // Generate type declarations for all Electric types
    output.push_str("// Electric row types\n");
    let type_decls = vec![
        serde_json::Value::decl(),
        Project::decl(),
        Notification::decl(),
        NotificationGroupKind::decl(),
        NotificationPayload::decl(),
        NotificationType::decl(),
        Workspace::decl(),
        ProjectStatus::decl(),
        Tag::decl(),
        Task::decl(),
        TaskAssignee::decl(),
        Blob::decl(),
        Attachment::decl(),
        AttachmentWithBlob::decl(),
        TaskFollower::decl(),
        TaskTag::decl(),
        TaskRelationship::decl(),
        TaskRelationshipType::decl(),
        TaskComment::decl(),
        TaskCommentReaction::decl(),
        TaskPriority::decl(),
        TaskSortField::decl(),
        ListTasksQuery::decl(),
        SearchTasksRequest::decl(),
        ListTasksResponse::decl(),
        PullRequestStatus::decl(),
        PullRequest::decl(),
        PullRequestTask::decl(),
        CreatePullRequestTaskRequest::decl(),
        SortDirection::decl(),
        UserData::decl(),
        User::decl(),
        RelayHost::decl(),
        ListRelayHostsResponse::decl(),
        CreateRemoteSessionResponse::decl(),
        MemberRole::decl(),
        OrganizationMember::decl(),
        // Mutation request types
        CreateProjectRequest::decl(),
        UpdateProjectRequest::decl(),
        UpdateNotificationRequest::decl(),
        CreateTagRequest::decl(),
        UpdateTagRequest::decl(),
        CreateProjectStatusRequest::decl(),
        UpdateProjectStatusRequest::decl(),
        CreateTaskRequest::decl(),
        UpdateTaskRequest::decl(),
        CreateTaskAssigneeRequest::decl(),
        CreateTaskFollowerRequest::decl(),
        CreateTaskTagRequest::decl(),
        CreateTaskRelationshipRequest::decl(),
        CreateTaskCommentRequest::decl(),
        UpdateTaskCommentRequest::decl(),
        CreateTaskCommentReactionRequest::decl(),
        UpdateTaskCommentReactionRequest::decl(),
        // Attachment API request/response types
        InitUploadRequest::decl(),
        InitUploadResponse::decl(),
        ConfirmUploadRequest::decl(),
        CommitAttachmentsRequest::decl(),
        CommitAttachmentsResponse::decl(),
        AttachmentUrlResponse::decl(),
        // Export API types
        ExportRequest::decl(),
    ];

    for decl in type_decls {
        let trimmed = decl
            .trim()
            .lines()
            .map(str::trim_end)
            .collect::<Vec<_>>()
            .join("\n");
        if trimmed.starts_with("export") {
            output.push_str(&trimmed);
        } else {
            output.push_str("export ");
            output.push_str(&trimmed);
        }
        output.push_str("\n\n");
    }

    // ShapeDefinition interface
    output.push_str("// Shape definition interface\n");
    output.push_str("export interface ShapeDefinition<T> {\n");
    output.push_str("  readonly table: string;\n");
    output.push_str("  readonly params: readonly string[];\n");
    output.push_str("  readonly url: string;\n");
    output.push_str("  readonly fallbackUrl: string;\n");
    output.push_str(
        "  readonly _type: T;  // Phantom field for type inference (not present at runtime)\n",
    );
    output.push_str("}\n\n");

    // Helper function
    output.push_str("// Helper to create type-safe shape definitions\n");
    output.push_str("function defineShape<T>(\n");
    output.push_str("  table: string,\n");
    output.push_str("  params: readonly string[],\n");
    output.push_str("  url: string,\n");
    output.push_str("  fallbackUrl: string\n");
    output.push_str("): ShapeDefinition<T> {\n");
    output.push_str("  return { table, params, url, fallbackUrl } as ShapeDefinition<T>;\n");
    output.push_str("}\n\n");

    // Generate individual shape definitions
    output.push_str("// Individual shape definitions with embedded types\n");
    for shape in &shapes {
        let name = shape.name();

        let params_str = shape
            .params()
            .iter()
            .map(|p| format!("'{}'", p))
            .collect::<Vec<_>>()
            .join(", ");

        output.push_str(&format!(
            "export const {} = defineShape<{}>(\n  '{}',\n  [{}] as const,\n  '/v1{}',\n  '/v1{}'\n);\n\n",
            name,
            shape.ts_type_name(),
            shape.table(),
            params_str,
            shape.url(),
            shape.fallback_url(),
        ));
    }

    output.push_str(
        "// =============================================================================\n",
    );
    output.push_str("// Mutation Definitions\n");
    output.push_str(
        "// =============================================================================\n\n",
    );

    // MutationDefinition interface
    output.push_str("// Mutation definition interface\n");
    output.push_str(
        "export interface MutationDefinition<TRow, TCreate = unknown, TUpdate = unknown> {\n",
    );
    output.push_str("  readonly name: string;\n");
    output.push_str("  readonly url: string;\n");
    output.push_str(
        "  readonly _rowType: TRow;  // Phantom field for type inference (not present at runtime)\n",
    );
    output.push_str("  readonly _createType: TCreate;  // Phantom field for type inference (not present at runtime)\n");
    output.push_str("  readonly _updateType: TUpdate;  // Phantom field for type inference (not present at runtime)\n");
    output.push_str("}\n\n");

    // Helper function
    output.push_str("// Helper to create type-safe mutation definitions\n");
    output.push_str("function defineMutation<TRow, TCreate, TUpdate>(\n");
    output.push_str("  name: string,\n");
    output.push_str("  url: string\n");
    output.push_str("): MutationDefinition<TRow, TCreate, TUpdate> {\n");
    output.push_str("  return { name, url } as MutationDefinition<TRow, TCreate, TUpdate>;\n");
    output.push_str("}\n\n");

    // Generate individual mutation definitions
    output.push_str("// Individual mutation definitions\n");
    for mutation in all_mutation_definitions() {
        let ts_type = &mutation.row_type;
        let const_name = to_screaming_snake_case(ts_type);
        let create_type = mutation.create_type.as_deref().unwrap_or("unknown");
        let update_type = mutation.update_type.as_deref().unwrap_or("unknown");

        output.push_str(&format!(
            "export const {}_MUTATION = defineMutation<{}, {}, {}>(\n  '{}',\n  '/v1/{}'\n);\n\n",
            const_name, ts_type, create_type, update_type, ts_type, mutation.table,
        ));
    }

    // Type helpers
    output.push_str("// Type helpers to extract types from a mutation definition\n");
    output.push_str("export type MutationRowType<M extends MutationDefinition<unknown>> = M extends MutationDefinition<infer R> ? R : never;\n");
    output.push_str("export type MutationCreateType<M extends MutationDefinition<unknown, unknown>> = M extends MutationDefinition<unknown, infer C> ? C : never;\n");
    output.push_str("export type MutationUpdateType<M extends MutationDefinition<unknown, unknown, unknown>> = M extends MutationDefinition<unknown, unknown, infer U> ? U : never;\n");

    output
}

/// Convert PascalCase to SCREAMING_SNAKE_CASE
fn to_screaming_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(c.to_ascii_uppercase());
    }
    result
}
